In [1]:
%pip install ../../../

Processing /home/sjoshi/spuco
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
  Created wheel for spuco: filename=spuco-0.0.1-py3-none-any.whl size=67507 sha256=30310e7ea7441d63b6b354b36c667744e726fa897cfbf8973542c55c8a62fab7
  Stored in directory: /tmp/pip-ephem-wheel-cache-44pfbhrz/wheels/ef/5d/43/a265894b1d52121a51705a208277e8d9a9670e95fa1a2e7ae6
Successfully built spuco
  Attempting uninstall: spuco
    Found existing installation: spuco 0.0.1
    Uninstalling spuco-0.0.1:
      Successfully uninstalled spuco-0.0.1
Note: you may need to restart the kernel to use updated packages.


In [2]:
import torch 

device = torch.device("cuda:7")

In [3]:
from spuco.datasets import SpuCoMNIST, SpuriousFeatureDifficulty
import torchvision.transforms as T

classes = [[0, 1], [2, 3], [4, 5], [6, 7], [8, 9]]
difficulty = SpuriousFeatureDifficulty.MAGNITUDE_EASY

trainset = SpuCoMNIST(
    root="/data/mnist/",
    spurious_feature_difficulty=difficulty,
    spurious_correlation_strength=0.99,
    classes=classes,
    split="train"
)
trainset.initialize()

testset = SpuCoMNIST(
    root="/data/mnist/",
    spurious_feature_difficulty=difficulty,
    classes=classes,
    split="test"
)
testset.initialize()

In [4]:
from spuco.datasets import SpuCoMNIST, SpuriousFeatureDifficulty
import torchvision.transforms as T

classes = [[0, 1], [2, 3], [4, 5], [6, 7], [8, 9]]
difficulty = SpuriousFeatureDifficulty.MAGNITUDE_EASY

valset = SpuCoMNIST(
    root="/data/mnist/",
    spurious_feature_difficulty=difficulty,
    classes=classes,
    split="val"
)
valset.initialize()

In [5]:
T.ToPILImage()(trainset[1000][0]).resize((28,28))

In [6]:
from spuco.models import model_factory 
model = model_factory("lenet", trainset[0][0].shape, trainset.num_spurious).to(device)

In [7]:
from spuco.group_inference import SSA
from spuco.utils import SpuriousTargetDataset

ssa = SSA(
    spurious_unlabeled_dataset=trainset,
    spurious_labeled_dataset=SpuriousTargetDataset(valset, valset.spurious),
    model=model,
    labeled_valset_size=0.2,
    num_iters=100,
    tau_g_min=0.1,
    device=device,
    verbose=True
)

In [8]:
group_partition = ssa.infer_groups()
for key in sorted(group_partition.keys()):
    print(key, len(group_partition[key]))

Training SSA Model 0:   1%|          | 1/100 [00:00<01:16,  1.30it/s, loss=nan, val_acc=20.2]

tensor([[-0.0862, -0.0708,  0.0450, -0.0856, -0.0986],
        [-0.0902, -0.0763,  0.0366, -0.0857, -0.0990],
        [-0.0872, -0.0801,  0.0437, -0.0815, -0.0926],
        [-0.0885, -0.0773,  0.0451, -0.0861, -0.0979],
        [-0.0893, -0.0774,  0.0502, -0.0885, -0.0991],
        [-0.0831, -0.0735,  0.0382, -0.0961, -0.0943],
        [-0.0903, -0.0746,  0.0412, -0.0871, -0.0969],
        [-0.0883, -0.0773,  0.0385, -0.0838, -0.0979],
        [-0.0900, -0.0729,  0.0431, -0.0798, -0.0971],
        [-0.0886, -0.0771,  0.0456, -0.0826, -0.0969],
        [-0.0866, -0.0718,  0.0382, -0.0875, -0.1005],
        [-0.0937, -0.0854,  0.0536, -0.0795, -0.1034],
        [-0.0916, -0.0786,  0.0484, -0.0866, -0.1017],
        [-0.0855, -0.0728,  0.0444, -0.0875, -0.0925],
        [-0.0909, -0.0809,  0.0494, -0.0824, -0.1027],
        [-0.0885, -0.0738,  0.0413, -0.0915, -0.0942],
        [-0.0898, -0.0707,  0.0459, -0.0822, -0.1002],
        [-0.0923, -0.0808,  0.0482, -0.0876, -0.0983],
        [-

Training SSA Model 0:   7%|▋         | 7/100 [00:01<00:09,  9.88it/s, loss=nan, val_acc=20.2]

tensor([[-0.0883, -0.0818,  0.0473, -0.0833, -0.0985],
        [-0.0886, -0.0731,  0.0333, -0.0838, -0.0967],
        [-0.0882, -0.0750,  0.0376, -0.0849, -0.0989],
        [-0.0813, -0.0749,  0.0413, -0.0867, -0.0922],
        [-0.0876, -0.0744,  0.0460, -0.0896, -0.0981],
        [-0.0902, -0.0837,  0.0476, -0.0838, -0.1024],
        [-0.0882, -0.0718,  0.0449, -0.0910, -0.0944],
        [-0.0958, -0.0804,  0.0465, -0.0890, -0.0993],
        [-0.0861, -0.0721,  0.0412, -0.0864, -0.0963],
        [-0.0875, -0.0743,  0.0394, -0.0879, -0.0925],
        [-0.0972, -0.0810,  0.0486, -0.0868, -0.1012],
        [-0.0934, -0.0830,  0.0471, -0.0854, -0.0989],
        [-0.0893, -0.0777,  0.0371, -0.0883, -0.0989],
        [-0.0885, -0.0763,  0.0442, -0.0838, -0.0977],
        [-0.0904, -0.0808,  0.0496, -0.0833, -0.0967],
        [-0.0915, -0.0819,  0.0434, -0.0829, -0.0997],
        [-0.0899, -0.0750,  0.0425, -0.0865, -0.0968],
        [-0.0865, -0.0845,  0.0464, -0.0842, -0.0967],
        [-

Training SSA Model 0:  13%|█▎        | 13/100 [00:01<00:05, 16.85it/s, loss=nan, val_acc=20.2]

tensor([[-0.0837, -0.0817,  0.0425, -0.0824, -0.0973],
        [-0.0929, -0.0759,  0.0349, -0.0843, -0.0990],
        [-0.0914, -0.0765,  0.0422, -0.0806, -0.0959],
        [-0.0917, -0.0807,  0.0477, -0.0815, -0.0993],
        [-0.0926, -0.0794,  0.0466, -0.0817, -0.0994],
        [-0.0999, -0.0828,  0.0468, -0.0814, -0.1054],
        [-0.0892, -0.0727,  0.0413, -0.0842, -0.0962],
        [-0.0917, -0.0752,  0.0485, -0.0851, -0.0987],
        [-0.0909, -0.0781,  0.0390, -0.0853, -0.1014],
        [-0.0912, -0.0765,  0.0383, -0.0819, -0.0975],
        [-0.0898, -0.0765,  0.0428, -0.0819, -0.0988],
        [-0.0884, -0.0727,  0.0375, -0.0848, -0.0948],
        [-0.0909, -0.0758,  0.0379, -0.0786, -0.1005],
        [-0.0926, -0.0812,  0.0473, -0.0778, -0.1058],
        [-0.0938, -0.0818,  0.0450, -0.0815, -0.0971],
        [-0.0915, -0.0783,  0.0401, -0.0819, -0.1001],
        [-0.0805, -0.0811,  0.0443, -0.0817, -0.0916],
        [-0.0938, -0.0836,  0.0421, -0.0851, -0.0971],
        [-

Training SSA Model 0:  19%|█▉        | 19/100 [00:01<00:03, 21.65it/s, loss=nan, val_acc=20.2]

tensor([[-0.0913, -0.0775,  0.0372, -0.0801, -0.0990],
        [-0.0891, -0.0773,  0.0378, -0.0767, -0.0947],
        [-0.0855, -0.0720,  0.0362, -0.0821, -0.0991],
        [-0.0910, -0.0790,  0.0395, -0.0765, -0.0946],
        [-0.0862, -0.0814,  0.0396, -0.0758, -0.0939],
        [-0.0854, -0.0698,  0.0389, -0.0815, -0.0973],
        [-0.0921, -0.0752,  0.0332, -0.0759, -0.1004],
        [-0.0891, -0.0754,  0.0394, -0.0836, -0.0974],
        [-0.0918, -0.0823,  0.0411, -0.0834, -0.0911],
        [-0.0874, -0.0778,  0.0324, -0.0780, -0.1011],
        [-0.0926, -0.0812,  0.0435, -0.0757, -0.0998],
        [-0.0955, -0.0821,  0.0405, -0.0755, -0.1008],
        [-0.0910, -0.0792,  0.0391, -0.0819, -0.0941],
        [-0.0888, -0.0779,  0.0432, -0.0798, -0.0996],
        [-0.0885, -0.0812,  0.0438, -0.0782, -0.0953],
        [-0.0949, -0.0806,  0.0337, -0.0801, -0.1013],
        [-0.0890, -0.0814,  0.0378, -0.0782, -0.0912],
        [-0.0944, -0.0831,  0.0447, -0.0769, -0.0991],
        [-

Training SSA Model 0:  25%|██▌       | 25/100 [00:01<00:03, 24.21it/s, loss=nan, val_acc=20.2]

tensor([[-0.0887, -0.0748,  0.0324, -0.0792, -0.0959],
        [-0.0883, -0.0718,  0.0335, -0.0795, -0.0944],
        [-0.0915, -0.0735,  0.0328, -0.0749, -0.1018],
        [-0.0877, -0.0771,  0.0296, -0.0785, -0.0988],
        [-0.0906, -0.0824,  0.0267, -0.0692, -0.0998],
        [-0.0916, -0.0803,  0.0226, -0.0776, -0.0971],
        [-0.0869, -0.0754,  0.0320, -0.0776, -0.0990],
        [-0.0895, -0.0732,  0.0385, -0.0763, -0.0987],
        [-0.0901, -0.0816,  0.0321, -0.0724, -0.0959],
        [-0.0876, -0.0731,  0.0329, -0.0781, -0.0962],
        [-0.0870, -0.0824,  0.0340, -0.0779, -0.0989],
        [-0.0909, -0.0748,  0.0392, -0.0743, -0.0978],
        [-0.0921, -0.0856,  0.0358, -0.0728, -0.0994],
        [-0.0942, -0.0779,  0.0312, -0.0740, -0.0943],
        [-0.0944, -0.0870,  0.0350, -0.0746, -0.0963],
        [-0.0957, -0.0834,  0.0326, -0.0699, -0.0977],
        [-0.0866, -0.0710,  0.0228, -0.0769, -0.0904],
        [-0.0917, -0.0777,  0.0304, -0.0705, -0.0991],
        [-

Training SSA Model 0:  31%|███       | 31/100 [00:01<00:02, 25.48it/s, loss=nan, val_acc=20.2]

tensor([[-0.0980, -0.0883,  0.0298, -0.0678, -0.0983],
        [-0.0937, -0.0796,  0.0379, -0.0682, -0.1015],
        [-0.0981, -0.0786,  0.0204, -0.0671, -0.0949],
        [-0.0789, -0.0803,  0.0246, -0.0761, -0.0929],
        [-0.0925, -0.0818,  0.0187, -0.0756, -0.0882],
        [-0.0886, -0.0741,  0.0270, -0.0757, -0.0957],
        [-0.0859, -0.0731,  0.0215, -0.0775, -0.0966],
        [-0.0919, -0.0771,  0.0186, -0.0702, -0.0993],
        [-0.0918, -0.0717,  0.0254, -0.0723, -0.0972],
        [-0.1010, -0.0903,  0.0289, -0.0664, -0.0968],
        [-0.0971, -0.0824,  0.0249, -0.0652, -0.0973],
        [-0.0887, -0.0866,  0.0272, -0.0709, -0.0903],
        [-0.0904, -0.0779,  0.0323, -0.0690, -0.1010],
        [-0.0774, -0.0716,  0.0222, -0.0741, -0.0885],
        [-0.0924, -0.0849,  0.0249, -0.0709, -0.0876],
        [-0.0914, -0.0752,  0.0265, -0.0625, -0.1048],
        [-0.0950, -0.0837,  0.0222, -0.0707, -0.0928],
        [-0.0964, -0.0838,  0.0249, -0.0705, -0.0905],
        [-

Training SSA Model 0:  37%|███▋      | 37/100 [00:02<00:02, 26.30it/s, loss=nan, val_acc=20.2]

tensor([[-0.1000, -0.0835,  0.0196, -0.0576, -0.0941],
        [-0.0780, -0.0809,  0.0167, -0.0701, -0.0871],
        [-0.0961, -0.0749,  0.0136, -0.0709, -0.0836],
        [-0.0799, -0.0827,  0.0126, -0.0703, -0.0821],
        [-0.0986, -0.0791,  0.0192, -0.0516, -0.0988],
        [-0.0930, -0.0803,  0.0188, -0.0673, -0.1002],
        [-0.0977, -0.0870,  0.0123, -0.0634, -0.0893],
        [-0.1042, -0.0913,  0.0230, -0.0568, -0.0997],
        [-0.0881, -0.0730,  0.0179, -0.0747, -0.0925],
        [-0.0980, -0.0794,  0.0245, -0.0644, -0.0998],
        [-0.1007, -0.0818,  0.0195, -0.0561, -0.1026],
        [-0.0957, -0.0864,  0.0129, -0.0658, -0.0851],
        [-0.0888, -0.0754,  0.0218, -0.0682, -0.0969],
        [-0.1020, -0.0876,  0.0214, -0.0567, -0.0980],
        [-0.0920, -0.0859,  0.0181, -0.0637, -0.0856],
        [-0.0921, -0.0748,  0.0227, -0.0678, -0.0956],
        [-0.0802, -0.0820,  0.0138, -0.0706, -0.0853],
        [-0.1025, -0.0862,  0.0223, -0.0568, -0.0985],
        [-

Training SSA Model 0:  43%|████▎     | 43/100 [00:02<00:02, 26.38it/s, loss=nan, val_acc=20.2]

tensor([[-1.0105e-01, -8.2613e-02,  1.4948e-02, -5.6612e-02, -1.0272e-01],
        [-1.0488e-01, -8.3591e-02,  1.6797e-02, -5.3410e-02, -1.0378e-01],
        [-9.5228e-02, -7.7778e-02,  2.1388e-02, -6.2716e-02, -9.8189e-02],
        [-1.0030e-01, -9.2171e-02,  8.0319e-03, -5.2766e-02, -8.4845e-02],
        [-9.3879e-02, -7.7410e-02, -2.7309e-03, -5.9968e-02, -8.6648e-02],
        [-1.1175e-01, -8.8688e-02,  1.0005e-02, -4.2181e-02, -9.7911e-02],
        [-1.0570e-01, -8.8619e-02,  9.0851e-03, -4.8014e-02, -9.6251e-02],
        [-1.0092e-01, -8.1941e-02,  1.7495e-02, -5.4000e-02, -1.0207e-01],
        [-1.0898e-01, -9.5739e-02,  1.4572e-02, -4.6350e-02, -9.5831e-02],
        [-8.5943e-02, -7.5794e-02, -3.4861e-03, -5.9864e-02, -8.3580e-02],
        [-1.0066e-01, -8.8354e-02,  6.3770e-03, -5.0846e-02, -8.3944e-02],
        [-1.0084e-01, -8.8907e-02,  5.2526e-03, -4.8621e-02, -8.2084e-02],
        [-1.0167e-01, -7.8744e-02,  2.1926e-02, -5.2389e-02, -1.0078e-01],
        [-8.5136e-02, -7.

Training SSA Model 0:  49%|████▉     | 49/100 [00:02<00:01, 26.89it/s, loss=nan, val_acc=20.2]

tensor([[-0.0853, -0.0792, -0.0084, -0.0497, -0.0776],
        [-0.1063, -0.0792,  0.0142, -0.0404, -0.1062],
        [-0.0920, -0.0802, -0.0069, -0.0468, -0.0819],
        [-0.1053, -0.0767,  0.0066, -0.0517, -0.1026],
        [-0.1166, -0.0988,  0.0072, -0.0269, -0.0978],
        [-0.1094, -0.1002, -0.0043, -0.0395, -0.0836],
        [-0.1092, -0.0863,  0.0156, -0.0415, -0.1047],
        [-0.1057, -0.0985, -0.0070, -0.0414, -0.0821],
        [-0.0796, -0.0798, -0.0071, -0.0570, -0.0825],
        [-0.0748, -0.0794,  0.0008, -0.0589, -0.0863],
        [-0.1081, -0.0947, -0.0066, -0.0361, -0.0835],
        [-0.1016, -0.0805,  0.0145, -0.0465, -0.1019],
        [-0.1059, -0.0835,  0.0169, -0.0477, -0.1049],
        [-0.1007, -0.0973,  0.0016, -0.0422, -0.0839],
        [-0.0773, -0.0828, -0.0008, -0.0545, -0.0841],
        [-0.0938, -0.0777, -0.0162, -0.0522, -0.0886],
        [-0.0821, -0.0790, -0.0007, -0.0521, -0.0840],
        [-0.1081, -0.0759,  0.0099, -0.0450, -0.1053],
        [-

Training SSA Model 0:  55%|█████▌    | 55/100 [00:02<00:01, 27.01it/s, loss=nan, val_acc=40.4]

tensor([[-0.1289, -0.1069, -0.0024, -0.0122, -0.1000],
        [-0.0907, -0.0820, -0.0208, -0.0427, -0.0720],
        [-0.1121, -0.1001, -0.0227, -0.0327, -0.0811],
        [-0.1297, -0.1065, -0.0065, -0.0131, -0.0952],
        [-0.1309, -0.0995, -0.0089, -0.0172, -0.0977],
        [-0.0761, -0.0781, -0.0195, -0.0431, -0.0779],
        [-0.1045, -0.0793,  0.0088, -0.0390, -0.1018],
        [-0.1090, -0.1008, -0.0166, -0.0300, -0.0721],
        [-0.1191, -0.0917,  0.0052, -0.0229, -0.1091],
        [-0.0838, -0.0832, -0.0180, -0.0425, -0.0757],
        [-0.1178, -0.0878,  0.0091, -0.0265, -0.1066],
        [-0.1278, -0.1013, -0.0055, -0.0106, -0.1012],
        [-0.1200, -0.0894,  0.0050, -0.0202, -0.1072],
        [-0.0843, -0.0740, -0.0233, -0.0471, -0.0771],
        [-0.1186, -0.0887,  0.0091, -0.0224, -0.1093],
        [-0.1261, -0.0953, -0.0074, -0.0097, -0.0999],
        [-0.1168, -0.1025, -0.0150, -0.0284, -0.0827],
        [-0.1280, -0.1025, -0.0010, -0.0136, -0.0988],
        [-

Training SSA Model 0:  61%|██████    | 61/100 [00:03<00:01, 27.49it/s, loss=nan, val_acc=20.5]

tensor([[-0.1345, -0.0919,  0.0068, -0.0065, -0.1135],
        [-0.1389, -0.0926, -0.0039, -0.0081, -0.1099],
        [-0.1478, -0.1190, -0.0133,  0.0009, -0.0957],
        [-0.1241, -0.1113, -0.0372, -0.0174, -0.0719],
        [-0.0751, -0.0785, -0.0276, -0.0469, -0.0746],
        [-0.1234, -0.1101, -0.0318, -0.0185, -0.0680],
        [-0.1154, -0.0794, -0.0096, -0.0223, -0.0974],
        [-0.1134, -0.0830,  0.0013, -0.0322, -0.1026],
        [-0.1310, -0.0921,  0.0013, -0.0109, -0.1058],
        [-0.1172, -0.1067, -0.0323, -0.0214, -0.0748],
        [-0.1162, -0.0809, -0.0095, -0.0222, -0.1002],
        [-0.1329, -0.0961, -0.0005, -0.0085, -0.1067],
        [-0.1222, -0.0939,  0.0061, -0.0265, -0.1063],
        [-0.0917, -0.0792, -0.0352, -0.0374, -0.0677],
        [-0.1088, -0.0845, -0.0320, -0.0323, -0.0804],
        [-0.1287, -0.1081, -0.0329, -0.0174, -0.0786],
        [-0.0779, -0.0802, -0.0302, -0.0430, -0.0773],
        [-0.1361, -0.0937, -0.0018, -0.0073, -0.1083],
        [-

Training SSA Model 0:  67%|██████▋   | 67/100 [00:03<00:01, 27.41it/s, loss=nan, val_acc=20.2]

tensor([[-0.1467, -0.0979, -0.0029,  0.0041, -0.1106],
        [-0.1263, -0.1188, -0.0497, -0.0034, -0.0605],
        [-0.1655, -0.1257, -0.0297,  0.0217, -0.0944],
        [-0.1180, -0.0889, -0.0496, -0.0189, -0.0781],
        [-0.1222, -0.1143, -0.0450, -0.0051, -0.0563],
        [-0.1235, -0.1120, -0.0486, -0.0105, -0.0607],
        [-0.0734, -0.0795, -0.0428, -0.0374, -0.0640],
        [-0.1450, -0.1008, -0.0059,  0.0052, -0.1106],
        [-0.1130, -0.0885, -0.0472, -0.0188, -0.0691],
        [-0.1648, -0.1307, -0.0302,  0.0185, -0.0922],
        [-0.1273, -0.0898, -0.0076, -0.0232, -0.1050],
        [-0.1336, -0.1171, -0.0523, -0.0007, -0.0645],
        [-0.1524, -0.1005, -0.0115,  0.0073, -0.1106],
        [-0.1501, -0.1021, -0.0107,  0.0089, -0.1101],
        [-0.1146, -0.0706, -0.0129, -0.0196, -0.0988],
        [-0.1460, -0.0957, -0.0048,  0.0096, -0.1110],
        [-0.1296, -0.1171, -0.0452, -0.0024, -0.0637],
        [-0.1527, -0.1087, -0.0063,  0.0029, -0.1126],
        [-

Training SSA Model 0:  73%|███████▎  | 73/100 [00:03<00:00, 27.79it/s, loss=nan, val_acc=20.2]

tensor([[-0.1339, -0.1264, -0.0623,  0.0096, -0.0497],
        [-0.1269, -0.0787, -0.0174, -0.0120, -0.1043],
        [-0.1258, -0.0714, -0.0312, -0.0114, -0.1006],
        [-0.1396, -0.1256, -0.0691,  0.0065, -0.0563],
        [-0.1503, -0.1245, -0.0711,  0.0113, -0.0626],
        [-0.0663, -0.0776, -0.0615, -0.0349, -0.0588],
        [-0.0696, -0.0788, -0.0532, -0.0327, -0.0667],
        [-0.1916, -0.1408, -0.0385,  0.0502, -0.0963],
        [-0.1417, -0.1298, -0.0706,  0.0190, -0.0559],
        [-0.1329, -0.1243, -0.0608,  0.0115, -0.0500],
        [-0.1428, -0.1230, -0.0722,  0.0058, -0.0510],
        [-0.1496, -0.1027, -0.0152,  0.0100, -0.1089],
        [-0.1051, -0.0856, -0.0671, -0.0221, -0.0673],
        [-0.1679, -0.1053, -0.0112,  0.0303, -0.1180],
        [-0.1675, -0.1047, -0.0125,  0.0282, -0.1155],
        [-0.1018, -0.0946, -0.0614, -0.0106, -0.0589],
        [-0.1340, -0.0689, -0.0247, -0.0019, -0.1053],
        [-0.1357, -0.0846, -0.0179,  0.0002, -0.1060],
        [-

Training SSA Model 0:  79%|███████▉  | 79/100 [00:03<00:00, 21.68it/s, loss=nan, val_acc=20.2]


tensor([[-0.1505, -0.1342, -0.0878,  0.0255, -0.0448],
        [-0.2175, -0.1571, -0.0493,  0.0813, -0.0964],
        [-0.1924, -0.1087, -0.0129,  0.0529, -0.1282],
        [-0.0941, -0.0915, -0.0906, -0.0112, -0.0499],
        [-0.1604, -0.1396, -0.0853,  0.0274, -0.0496],
        [-0.1317, -0.0651, -0.0290, -0.0008, -0.1112],
        [-0.1940, -0.1116, -0.0134,  0.0463, -0.1241],
        [-0.1537, -0.1366, -0.0846,  0.0366, -0.0500],
        [-0.0955, -0.0926, -0.0816, -0.0074, -0.0524],
        [-0.1607, -0.0838, -0.0238,  0.0186, -0.1150],
        [-0.1517, -0.0800, -0.0260,  0.0139, -0.1151],
        [-0.1552, -0.1360, -0.0814,  0.0300, -0.0459],
        [-0.1678, -0.1460, -0.0791,  0.0362, -0.0589],
        [-0.1510, -0.1355, -0.0836,  0.0312, -0.0495],
        [-0.1567, -0.0890, -0.0236,  0.0085, -0.1121],
        [-0.2210, -0.1575, -0.0492,  0.0787, -0.0957],
        [-0.2173, -0.1594, -0.0444,  0.0738, -0.0963],
        [-0.2222, -0.1652, -0.0456,  0.0791, -0.0973],
        [-

IndexError: too many indices for tensor of dimension 2

In [ ]:
from spuco.evaluate import Evaluator 

evaluator = Evaluator(
    testset=trainset,
    group_partition=group_partition,
    group_weights=trainset.group_weights,
    batch_size=64,
    model=model,
    device=device,
    verbose=True
)
evaluator.evaluate()

In [ ]:
from torch.optim import SGD
from spuco.invariant_train import GroupBalanceERM, ClassBalanceERM
from spuco.models import model_factory 

model = model_factory("lenet", trainset[0][0].shape, trainset.num_classes).to(device)
group_balance_erm = GroupBalanceERM(
    model=model,
    num_epochs=5,
    trainset=trainset,
    group_partition=group_partition,
    batch_size=64,
    optimizer=SGD(model.parameters(), lr=1e-3, weight_decay=5e-4, momentum=0.9, nesterov=True),
    device=device,
    verbose=True
)
group_balance_erm.train()

In [ ]:
from spuco.evaluate import Evaluator

evaluator = Evaluator(
    testset=testset,
    group_partition=testset.group_partition,
    group_weights=trainset.group_weights,
    batch_size=64,
    model=model,
    device=device,
    verbose=True
)
evaluator.evaluate()

In [ ]:
evaluator.worst_group_accuracy

In [ ]:
evaluator.average_accuracy

In [ ]:
evaluator.evaluate_spurious_task()