In [11]:
%pip install ../../

Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Processing /home/yuyang/SpuCo
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
  Created wheel for spuco: filename=spuco-0.0.1-py3-none-any.whl size=81064 sha256=246ec6ec1405192c7f23bf42ab1d28030f0850e8959b86c39071405a1d064445
  Stored in directory: /tmp/pip-ephem-wheel-cache-anrcr9jm/wheels/99/d4/10/c6136b4f67d7a1fd0d788e21f761b3004ee3bbbfae90fc0ca1
Successfully built spuco
  Attempting uninstall: spuco
    Found existing installation: spuco 0.0.1
    Uninstalling spuco-0.0.1:
      Successfully uninstalled spuco-0.0.1
Note: you may need to restart the kernel to use updated packages.


In [1]:
import torch 

device = torch.device("cuda:7")

In [2]:
from spuco.utils import set_seed

set_seed(0)

/home/yuyang/SpuCo/.conda/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
from wilds import get_dataset
import torchvision.transforms as transforms

# Load the full dataset, and download it if necessary
dataset = get_dataset(dataset="waterbirds", download=True, root_dir="/data")

transform = transforms.Compose([
            transforms.Resize(256),
            transforms.CenterCrop(224),
            transforms.ToTensor(),
            transforms.Normalize((0.485, 0.456, 0.406), (0.229, 0.224, 0.225))
        ])

# Get the training set
train_data = dataset.get_subset(
    "train",
    transform=transform
)

# Get the training set
test_data = dataset.get_subset(
    "test",
    transform=transform
)

In [4]:
from spuco.utils import WILDSDatasetWrapper

trainset = WILDSDatasetWrapper(dataset=train_data, metadata_spurious_label="background", verbose=True)
testset = WILDSDatasetWrapper(dataset=test_data, metadata_spurious_label="background", verbose=True)

Partitioning data indices into groups: 100%|██████████| 5794/5794 [00:00<00:00, 2215296.02it/s]


In [5]:
trainset.group_weights

{(1, 1): 0.22043795620437956,
 (1, 0): 0.01167883211678832,
 (0, 0): 0.7295099061522419,
 (0, 1): 0.0383733055265902}

In [6]:
from spuco.utils import GroupLabeledDataset

invariant_trainset = GroupLabeledDataset(trainset, trainset.group_partition)

In [7]:
from spuco.models import model_factory 

model = model_factory("resnet50", trainset[0][0].shape, trainset.num_classes).to(device)

/home/yuyang/SpuCo/.conda/lib/python3.10/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/yuyang/SpuCo/.conda/lib/python3.10/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


In [8]:
from torch.optim import SGD
from spuco.invariant_train import GroupDRO 

group_dro = GroupDRO(
    model=model,
    num_epochs=300,
    trainset=invariant_trainset,
    batch_size=128,
    optimizer=SGD(model.parameters(), lr=1e-5, weight_decay=1.0, momentum=0.9),
    device=device,
    verbose=True
)
group_dro.train()

Epoch 0: 100%|██████████| 38/38 [00:13<00:00,  2.83batch/s, accuracy=35.59322033898305%, loss=0.719]


tensor([0.2419, 0.2365, 0.2585, 0.2631], device='cuda:7')


Epoch 1: 100%|██████████| 38/38 [00:10<00:00,  3.49batch/s, accuracy=50.847457627118644%, loss=0.709]


tensor([0.2426, 0.2321, 0.2584, 0.2669], device='cuda:7')


Epoch 2: 100%|██████████| 38/38 [00:10<00:00,  3.50batch/s, accuracy=62.71186440677966%, loss=0.681]


tensor([0.2479, 0.2323, 0.2538, 0.2660], device='cuda:7')


Epoch 3: 100%|██████████| 38/38 [00:10<00:00,  3.47batch/s, accuracy=67.79661016949153%, loss=0.645]


tensor([0.2544, 0.2337, 0.2480, 0.2639], device='cuda:7')


Epoch 4: 100%|██████████| 38/38 [00:10<00:00,  3.51batch/s, accuracy=47.45762711864407%, loss=0.702]


tensor([0.2599, 0.2347, 0.2437, 0.2617], device='cuda:7')


Epoch 5: 100%|██████████| 38/38 [00:10<00:00,  3.46batch/s, accuracy=59.32203389830509%, loss=0.653]


tensor([0.2640, 0.2350, 0.2394, 0.2615], device='cuda:7')


Epoch 6: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=69.49152542372882%, loss=0.637]


tensor([0.2671, 0.2350, 0.2365, 0.2614], device='cuda:7')


Epoch 7: 100%|██████████| 38/38 [00:10<00:00,  3.50batch/s, accuracy=64.40677966101696%, loss=0.622]


tensor([0.2681, 0.2351, 0.2348, 0.2620], device='cuda:7')


Epoch 8: 100%|██████████| 38/38 [00:10<00:00,  3.47batch/s, accuracy=76.27118644067797%, loss=0.609]


tensor([0.2694, 0.2345, 0.2333, 0.2629], device='cuda:7')


Epoch 9: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=81.35593220338983%, loss=0.596]


tensor([0.2700, 0.2343, 0.2319, 0.2639], device='cuda:7')


Epoch 10: 100%|██████████| 38/38 [00:10<00:00,  3.47batch/s, accuracy=83.05084745762711%, loss=0.582]


tensor([0.2701, 0.2336, 0.2308, 0.2655], device='cuda:7')


Epoch 11: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=79.66101694915254%, loss=0.573]


tensor([0.2701, 0.2336, 0.2295, 0.2669], device='cuda:7')


Epoch 12: 100%|██████████| 38/38 [00:10<00:00,  3.46batch/s, accuracy=91.52542372881356%, loss=0.56]


tensor([0.2692, 0.2343, 0.2287, 0.2677], device='cuda:7')


Epoch 13: 100%|██████████| 38/38 [00:10<00:00,  3.54batch/s, accuracy=74.57627118644068%, loss=0.562]


tensor([0.2693, 0.2345, 0.2280, 0.2682], device='cuda:7')


Epoch 14: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=77.96610169491525%, loss=0.593]


tensor([0.2694, 0.2347, 0.2279, 0.2680], device='cuda:7')


Epoch 15: 100%|██████████| 38/38 [00:10<00:00,  3.49batch/s, accuracy=79.66101694915254%, loss=0.566]


tensor([0.2683, 0.2353, 0.2280, 0.2684], device='cuda:7')


Epoch 16: 100%|██████████| 38/38 [00:10<00:00,  3.49batch/s, accuracy=81.35593220338983%, loss=0.526]


tensor([0.2676, 0.2357, 0.2271, 0.2697], device='cuda:7')


Epoch 17: 100%|██████████| 38/38 [00:11<00:00,  3.43batch/s, accuracy=84.7457627118644%, loss=0.54]


tensor([0.2666, 0.2362, 0.2269, 0.2703], device='cuda:7')


Epoch 18: 100%|██████████| 38/38 [00:11<00:00,  3.42batch/s, accuracy=93.22033898305085%, loss=0.504]


tensor([0.2658, 0.2371, 0.2267, 0.2704], device='cuda:7')


Epoch 19: 100%|██████████| 38/38 [00:11<00:00,  3.44batch/s, accuracy=84.7457627118644%, loss=0.52]


tensor([0.2648, 0.2380, 0.2263, 0.2709], device='cuda:7')


Epoch 20: 100%|██████████| 38/38 [00:10<00:00,  3.47batch/s, accuracy=86.44067796610169%, loss=0.511]


tensor([0.2636, 0.2392, 0.2259, 0.2713], device='cuda:7')


Epoch 21: 100%|██████████| 38/38 [00:10<00:00,  3.49batch/s, accuracy=93.22033898305085%, loss=0.509]


tensor([0.2620, 0.2405, 0.2259, 0.2716], device='cuda:7')


Epoch 22: 100%|██████████| 38/38 [00:11<00:00,  3.45batch/s, accuracy=94.91525423728814%, loss=0.465]


tensor([0.2609, 0.2419, 0.2255, 0.2717], device='cuda:7')


Epoch 23: 100%|██████████| 38/38 [00:10<00:00,  3.50batch/s, accuracy=94.91525423728814%, loss=0.489]


tensor([0.2589, 0.2438, 0.2254, 0.2720], device='cuda:7')


Epoch 24: 100%|██████████| 38/38 [00:10<00:00,  3.47batch/s, accuracy=91.52542372881356%, loss=0.483]


tensor([0.2573, 0.2448, 0.2248, 0.2731], device='cuda:7')


Epoch 25: 100%|██████████| 38/38 [00:10<00:00,  3.52batch/s, accuracy=88.13559322033899%, loss=0.475]


tensor([0.2555, 0.2464, 0.2243, 0.2737], device='cuda:7')


Epoch 26: 100%|██████████| 38/38 [00:10<00:00,  3.46batch/s, accuracy=84.7457627118644%, loss=0.492]


tensor([0.2540, 0.2485, 0.2241, 0.2735], device='cuda:7')


Epoch 27: 100%|██████████| 38/38 [00:10<00:00,  3.46batch/s, accuracy=89.83050847457628%, loss=0.489]


tensor([0.2526, 0.2502, 0.2232, 0.2741], device='cuda:7')


Epoch 28: 100%|██████████| 38/38 [00:10<00:00,  3.49batch/s, accuracy=89.83050847457628%, loss=0.473]


tensor([0.2503, 0.2519, 0.2237, 0.2741], device='cuda:7')


Epoch 29: 100%|██████████| 38/38 [00:10<00:00,  3.49batch/s, accuracy=86.44067796610169%, loss=0.5]


tensor([0.2485, 0.2539, 0.2231, 0.2745], device='cuda:7')


Epoch 30: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=93.22033898305085%, loss=0.458]


tensor([0.2469, 0.2555, 0.2222, 0.2754], device='cuda:7')


Epoch 31: 100%|██████████| 38/38 [00:10<00:00,  3.49batch/s, accuracy=88.13559322033899%, loss=0.471]


tensor([0.2457, 0.2563, 0.2216, 0.2764], device='cuda:7')


Epoch 32: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=86.44067796610169%, loss=0.4]


tensor([0.2440, 0.2578, 0.2211, 0.2771], device='cuda:7')


Epoch 33: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=83.05084745762711%, loss=0.466]


tensor([0.2428, 0.2595, 0.2197, 0.2781], device='cuda:7')


Epoch 34: 100%|██████████| 38/38 [00:10<00:00,  3.49batch/s, accuracy=89.83050847457628%, loss=0.419]


tensor([0.2406, 0.2616, 0.2188, 0.2790], device='cuda:7')


Epoch 35: 100%|██████████| 38/38 [00:10<00:00,  3.49batch/s, accuracy=93.22033898305085%, loss=0.421]


tensor([0.2380, 0.2628, 0.2184, 0.2808], device='cuda:7')


Epoch 36: 100%|██████████| 38/38 [00:11<00:00,  3.41batch/s, accuracy=96.61016949152543%, loss=0.397]


tensor([0.2370, 0.2638, 0.2175, 0.2817], device='cuda:7')


Epoch 37: 100%|██████████| 38/38 [00:11<00:00,  3.45batch/s, accuracy=93.22033898305085%, loss=0.398]


tensor([0.2360, 0.2656, 0.2165, 0.2819], device='cuda:7')


Epoch 38: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=93.22033898305085%, loss=0.414]


tensor([0.2351, 0.2675, 0.2144, 0.2829], device='cuda:7')


Epoch 39: 100%|██████████| 38/38 [00:11<00:00,  3.45batch/s, accuracy=86.44067796610169%, loss=0.407]


tensor([0.2340, 0.2682, 0.2142, 0.2836], device='cuda:7')


Epoch 40: 100%|██████████| 38/38 [00:10<00:00,  3.50batch/s, accuracy=94.91525423728814%, loss=0.421]


tensor([0.2326, 0.2696, 0.2136, 0.2842], device='cuda:7')


Epoch 41: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=94.91525423728814%, loss=0.381]


tensor([0.2310, 0.2714, 0.2125, 0.2851], device='cuda:7')


Epoch 42: 100%|██████████| 38/38 [00:10<00:00,  3.49batch/s, accuracy=94.91525423728814%, loss=0.376]


tensor([0.2287, 0.2724, 0.2116, 0.2873], device='cuda:7')


Epoch 43: 100%|██████████| 38/38 [00:10<00:00,  3.47batch/s, accuracy=91.52542372881356%, loss=0.392]


tensor([0.2268, 0.2739, 0.2108, 0.2886], device='cuda:7')


Epoch 44: 100%|██████████| 38/38 [00:10<00:00,  3.50batch/s, accuracy=89.83050847457628%, loss=0.367]


tensor([0.2253, 0.2749, 0.2095, 0.2902], device='cuda:7')


Epoch 45: 100%|██████████| 38/38 [00:10<00:00,  3.49batch/s, accuracy=91.52542372881356%, loss=0.391]


tensor([0.2236, 0.2748, 0.2090, 0.2926], device='cuda:7')


Epoch 46: 100%|██████████| 38/38 [00:10<00:00,  3.50batch/s, accuracy=96.61016949152543%, loss=0.406]


tensor([0.2219, 0.2771, 0.2078, 0.2932], device='cuda:7')


Epoch 47: 100%|██████████| 38/38 [00:10<00:00,  3.49batch/s, accuracy=88.13559322033899%, loss=0.386]


tensor([0.2212, 0.2790, 0.2065, 0.2933], device='cuda:7')


Epoch 48: 100%|██████████| 38/38 [00:10<00:00,  3.50batch/s, accuracy=96.61016949152543%, loss=0.362]


tensor([0.2193, 0.2808, 0.2048, 0.2951], device='cuda:7')


Epoch 49: 100%|██████████| 38/38 [00:10<00:00,  3.49batch/s, accuracy=88.13559322033899%, loss=0.391]


tensor([0.2176, 0.2820, 0.2034, 0.2970], device='cuda:7')


Epoch 50: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=84.7457627118644%, loss=0.44]


tensor([0.2164, 0.2830, 0.2020, 0.2987], device='cuda:7')


Epoch 51: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=88.13559322033899%, loss=0.35]


tensor([0.2150, 0.2833, 0.2003, 0.3013], device='cuda:7')


Epoch 52: 100%|██████████| 38/38 [00:10<00:00,  3.52batch/s, accuracy=91.52542372881356%, loss=0.335]


tensor([0.2135, 0.2850, 0.1978, 0.3036], device='cuda:7')


Epoch 53: 100%|██████████| 38/38 [00:10<00:00,  3.47batch/s, accuracy=88.13559322033899%, loss=0.383]


tensor([0.2135, 0.2860, 0.1955, 0.3050], device='cuda:7')


Epoch 54: 100%|██████████| 38/38 [00:10<00:00,  3.47batch/s, accuracy=86.44067796610169%, loss=0.387]


tensor([0.2128, 0.2868, 0.1937, 0.3067], device='cuda:7')


Epoch 55: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=89.83050847457628%, loss=0.376]


tensor([0.2121, 0.2861, 0.1923, 0.3094], device='cuda:7')


Epoch 56: 100%|██████████| 38/38 [00:11<00:00,  3.45batch/s, accuracy=84.7457627118644%, loss=0.348]


tensor([0.2115, 0.2876, 0.1902, 0.3107], device='cuda:7')


Epoch 57: 100%|██████████| 38/38 [00:10<00:00,  3.47batch/s, accuracy=91.52542372881356%, loss=0.376]


tensor([0.2108, 0.2892, 0.1882, 0.3118], device='cuda:7')


Epoch 58: 100%|██████████| 38/38 [00:11<00:00,  3.44batch/s, accuracy=86.44067796610169%, loss=0.328]


tensor([0.2096, 0.2896, 0.1866, 0.3142], device='cuda:7')


Epoch 59: 100%|██████████| 38/38 [00:10<00:00,  3.47batch/s, accuracy=86.44067796610169%, loss=0.388]


tensor([0.2091, 0.2904, 0.1843, 0.3162], device='cuda:7')


Epoch 60: 100%|██████████| 38/38 [00:10<00:00,  3.49batch/s, accuracy=84.7457627118644%, loss=0.396]


tensor([0.2079, 0.2920, 0.1824, 0.3177], device='cuda:7')


Epoch 61: 100%|██████████| 38/38 [00:11<00:00,  3.45batch/s, accuracy=93.22033898305085%, loss=0.373]


tensor([0.2069, 0.2918, 0.1812, 0.3201], device='cuda:7')


Epoch 62: 100%|██████████| 38/38 [00:11<00:00,  3.40batch/s, accuracy=91.52542372881356%, loss=0.305]


tensor([0.2058, 0.2922, 0.1798, 0.3222], device='cuda:7')


Epoch 63: 100%|██████████| 38/38 [00:11<00:00,  3.45batch/s, accuracy=88.13559322033899%, loss=0.373]


tensor([0.2045, 0.2937, 0.1779, 0.3238], device='cuda:7')


Epoch 64: 100%|██████████| 38/38 [00:10<00:00,  3.47batch/s, accuracy=94.91525423728814%, loss=0.338]


tensor([0.2038, 0.2943, 0.1760, 0.3259], device='cuda:7')


Epoch 65: 100%|██████████| 38/38 [00:11<00:00,  3.45batch/s, accuracy=89.83050847457628%, loss=0.375]


tensor([0.2024, 0.2948, 0.1739, 0.3289], device='cuda:7')


Epoch 66: 100%|██████████| 38/38 [00:10<00:00,  3.46batch/s, accuracy=89.83050847457628%, loss=0.341]


tensor([0.2012, 0.2954, 0.1720, 0.3313], device='cuda:7')


Epoch 67: 100%|██████████| 38/38 [00:10<00:00,  3.51batch/s, accuracy=89.83050847457628%, loss=0.354]


tensor([0.1997, 0.2957, 0.1696, 0.3350], device='cuda:7')


Epoch 68: 100%|██████████| 38/38 [00:10<00:00,  3.47batch/s, accuracy=91.52542372881356%, loss=0.293]


tensor([0.1994, 0.2961, 0.1674, 0.3371], device='cuda:7')


Epoch 69: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=89.83050847457628%, loss=0.33]


tensor([0.1981, 0.2967, 0.1652, 0.3401], device='cuda:7')


Epoch 70: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=91.52542372881356%, loss=0.35]


tensor([0.1974, 0.2971, 0.1635, 0.3420], device='cuda:7')


Epoch 71: 100%|██████████| 38/38 [00:10<00:00,  3.46batch/s, accuracy=98.30508474576271%, loss=0.284]


tensor([0.1974, 0.2982, 0.1615, 0.3430], device='cuda:7')


Epoch 72: 100%|██████████| 38/38 [00:10<00:00,  3.47batch/s, accuracy=94.91525423728814%, loss=0.275]


tensor([0.1969, 0.2993, 0.1598, 0.3440], device='cuda:7')


Epoch 73: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=91.52542372881356%, loss=0.321]


tensor([0.1964, 0.3000, 0.1575, 0.3460], device='cuda:7')


Epoch 74: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=86.44067796610169%, loss=0.398]


tensor([0.1955, 0.3005, 0.1553, 0.3487], device='cuda:7')


Epoch 75: 100%|██████████| 38/38 [00:10<00:00,  3.46batch/s, accuracy=86.44067796610169%, loss=0.377]


tensor([0.1946, 0.3011, 0.1525, 0.3518], device='cuda:7')


Epoch 76: 100%|██████████| 38/38 [00:11<00:00,  3.44batch/s, accuracy=88.13559322033899%, loss=0.35]


tensor([0.1942, 0.3013, 0.1507, 0.3538], device='cuda:7')


Epoch 77: 100%|██████████| 38/38 [00:10<00:00,  3.46batch/s, accuracy=94.91525423728814%, loss=0.292]


tensor([0.1938, 0.3021, 0.1489, 0.3551], device='cuda:7')


Epoch 78: 100%|██████████| 38/38 [00:11<00:00,  3.45batch/s, accuracy=93.22033898305085%, loss=0.32]


tensor([0.1938, 0.3023, 0.1472, 0.3567], device='cuda:7')


Epoch 79: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=93.22033898305085%, loss=0.353]


tensor([0.1930, 0.3011, 0.1457, 0.3602], device='cuda:7')


Epoch 80: 100%|██████████| 38/38 [00:11<00:00,  3.44batch/s, accuracy=93.22033898305085%, loss=0.297]


tensor([0.1929, 0.3017, 0.1435, 0.3619], device='cuda:7')


Epoch 81: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=93.22033898305085%, loss=0.309]


tensor([0.1924, 0.3015, 0.1410, 0.3650], device='cuda:7')


Epoch 82: 100%|██████████| 38/38 [00:10<00:00,  3.50batch/s, accuracy=94.91525423728814%, loss=0.314]


tensor([0.1917, 0.3013, 0.1390, 0.3681], device='cuda:7')


Epoch 83: 100%|██████████| 38/38 [00:10<00:00,  3.50batch/s, accuracy=94.91525423728814%, loss=0.284]


tensor([0.1921, 0.3021, 0.1372, 0.3686], device='cuda:7')


Epoch 84: 100%|██████████| 38/38 [00:10<00:00,  3.53batch/s, accuracy=98.30508474576271%, loss=0.254]


tensor([0.1923, 0.3022, 0.1353, 0.3702], device='cuda:7')


Epoch 85: 100%|██████████| 38/38 [00:10<00:00,  3.46batch/s, accuracy=100.0%, loss=0.246]   


tensor([0.1928, 0.3010, 0.1336, 0.3726], device='cuda:7')


Epoch 86: 100%|██████████| 38/38 [00:10<00:00,  3.47batch/s, accuracy=98.30508474576271%, loss=0.277]


tensor([0.1921, 0.3008, 0.1321, 0.3750], device='cuda:7')


Epoch 87: 100%|██████████| 38/38 [00:10<00:00,  3.49batch/s, accuracy=86.44067796610169%, loss=0.318]


tensor([0.1916, 0.3004, 0.1302, 0.3778], device='cuda:7')


Epoch 88: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=94.91525423728814%, loss=0.248]


tensor([0.1923, 0.3005, 0.1280, 0.3793], device='cuda:7')


Epoch 89: 100%|██████████| 38/38 [00:11<00:00,  3.45batch/s, accuracy=89.83050847457628%, loss=0.282]


tensor([0.1924, 0.2999, 0.1268, 0.3810], device='cuda:7')


Epoch 90: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=96.61016949152543%, loss=0.252]


tensor([0.1924, 0.3004, 0.1250, 0.3821], device='cuda:7')


Epoch 91: 100%|██████████| 38/38 [00:10<00:00,  3.47batch/s, accuracy=94.91525423728814%, loss=0.27]


tensor([0.1917, 0.2998, 0.1235, 0.3850], device='cuda:7')


Epoch 92: 100%|██████████| 38/38 [00:11<00:00,  3.45batch/s, accuracy=81.35593220338983%, loss=0.415]


tensor([0.1919, 0.3015, 0.1218, 0.3848], device='cuda:7')


Epoch 93: 100%|██████████| 38/38 [00:10<00:00,  3.52batch/s, accuracy=93.22033898305085%, loss=0.242]


tensor([0.1922, 0.3020, 0.1202, 0.3856], device='cuda:7')


Epoch 94: 100%|██████████| 38/38 [00:10<00:00,  3.47batch/s, accuracy=94.91525423728814%, loss=0.26]


tensor([0.1928, 0.3027, 0.1188, 0.3858], device='cuda:7')


Epoch 95: 100%|██████████| 38/38 [00:10<00:00,  3.49batch/s, accuracy=93.22033898305085%, loss=0.294]


tensor([0.1921, 0.3029, 0.1177, 0.3873], device='cuda:7')


Epoch 96: 100%|██████████| 38/38 [00:11<00:00,  3.45batch/s, accuracy=84.7457627118644%, loss=0.342]


tensor([0.1913, 0.3019, 0.1159, 0.3910], device='cuda:7')


Epoch 97: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=96.61016949152543%, loss=0.214]


tensor([0.1901, 0.3005, 0.1150, 0.3944], device='cuda:7')


Epoch 98: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=96.61016949152543%, loss=0.242]


tensor([0.1890, 0.2999, 0.1136, 0.3975], device='cuda:7')


Epoch 99: 100%|██████████| 38/38 [00:10<00:00,  3.51batch/s, accuracy=96.61016949152543%, loss=0.207]


tensor([0.1890, 0.3006, 0.1125, 0.3979], device='cuda:7')


Epoch 100: 100%|██████████| 38/38 [00:10<00:00,  3.49batch/s, accuracy=93.22033898305085%, loss=0.246]


tensor([0.1893, 0.3007, 0.1113, 0.3987], device='cuda:7')


Epoch 101: 100%|██████████| 38/38 [00:11<00:00,  3.45batch/s, accuracy=98.30508474576271%, loss=0.245]


tensor([0.1901, 0.3004, 0.1100, 0.3995], device='cuda:7')


Epoch 102: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=98.30508474576271%, loss=0.227]


tensor([0.1894, 0.2993, 0.1090, 0.4023], device='cuda:7')


Epoch 103: 100%|██████████| 38/38 [00:10<00:00,  3.47batch/s, accuracy=94.91525423728814%, loss=0.209]


tensor([0.1896, 0.2984, 0.1082, 0.4038], device='cuda:7')


Epoch 104: 100%|██████████| 38/38 [00:10<00:00,  3.51batch/s, accuracy=93.22033898305085%, loss=0.232]


tensor([0.1901, 0.2987, 0.1070, 0.4041], device='cuda:7')


Epoch 105: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=94.91525423728814%, loss=0.245]


tensor([0.1903, 0.2988, 0.1061, 0.4049], device='cuda:7')


Epoch 106: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=94.91525423728814%, loss=0.258]


tensor([0.1906, 0.2978, 0.1046, 0.4070], device='cuda:7')


Epoch 107: 100%|██████████| 38/38 [00:10<00:00,  3.51batch/s, accuracy=98.30508474576271%, loss=0.23]


tensor([0.1908, 0.2969, 0.1037, 0.4085], device='cuda:7')


Epoch 108: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=93.22033898305085%, loss=0.289]


tensor([0.1906, 0.2971, 0.1024, 0.4099], device='cuda:7')


Epoch 109: 100%|██████████| 38/38 [00:10<00:00,  3.46batch/s, accuracy=94.91525423728814%, loss=0.214]


tensor([0.1911, 0.2980, 0.1009, 0.4100], device='cuda:7')


Epoch 110: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=96.61016949152543%, loss=0.235]


tensor([0.1923, 0.2977, 0.0996, 0.4103], device='cuda:7')


Epoch 111: 100%|██████████| 38/38 [00:10<00:00,  3.50batch/s, accuracy=96.61016949152543%, loss=0.22]


tensor([0.1923, 0.2973, 0.0988, 0.4116], device='cuda:7')


Epoch 112: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=91.52542372881356%, loss=0.267]


tensor([0.1928, 0.2978, 0.0976, 0.4117], device='cuda:7')


Epoch 113: 100%|██████████| 38/38 [00:10<00:00,  3.49batch/s, accuracy=98.30508474576271%, loss=0.203]


tensor([0.1927, 0.2980, 0.0966, 0.4127], device='cuda:7')


Epoch 114: 100%|██████████| 38/38 [00:10<00:00,  3.46batch/s, accuracy=94.91525423728814%, loss=0.221]


tensor([0.1928, 0.2988, 0.0959, 0.4125], device='cuda:7')


Epoch 115: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=96.61016949152543%, loss=0.25]


tensor([0.1933, 0.2979, 0.0956, 0.4132], device='cuda:7')


Epoch 116: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=94.91525423728814%, loss=0.234]


tensor([0.1940, 0.2979, 0.0952, 0.4130], device='cuda:7')


Epoch 117: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=96.61016949152543%, loss=0.223]


tensor([0.1941, 0.2974, 0.0940, 0.4144], device='cuda:7')


Epoch 118: 100%|██████████| 38/38 [00:10<00:00,  3.47batch/s, accuracy=94.91525423728814%, loss=0.22]


tensor([0.1950, 0.2969, 0.0932, 0.4149], device='cuda:7')


Epoch 119: 100%|██████████| 38/38 [00:10<00:00,  3.47batch/s, accuracy=94.91525423728814%, loss=0.262]


tensor([0.1953, 0.2963, 0.0927, 0.4158], device='cuda:7')


Epoch 120: 100%|██████████| 38/38 [00:10<00:00,  3.50batch/s, accuracy=94.91525423728814%, loss=0.288]


tensor([0.1956, 0.2952, 0.0923, 0.4168], device='cuda:7')


Epoch 121: 100%|██████████| 38/38 [00:10<00:00,  3.51batch/s, accuracy=98.30508474576271%, loss=0.194]


tensor([0.1970, 0.2952, 0.0915, 0.4163], device='cuda:7')


Epoch 122: 100%|██████████| 38/38 [00:11<00:00,  3.45batch/s, accuracy=96.61016949152543%, loss=0.243]


tensor([0.1972, 0.2944, 0.0908, 0.4177], device='cuda:7')


Epoch 123: 100%|██████████| 38/38 [00:10<00:00,  3.47batch/s, accuracy=98.30508474576271%, loss=0.224]


tensor([0.1980, 0.2939, 0.0905, 0.4176], device='cuda:7')


Epoch 124: 100%|██████████| 38/38 [00:10<00:00,  3.50batch/s, accuracy=98.30508474576271%, loss=0.265]


tensor([0.1985, 0.2939, 0.0898, 0.4178], device='cuda:7')


Epoch 125: 100%|██████████| 38/38 [00:10<00:00,  3.47batch/s, accuracy=94.91525423728814%, loss=0.259]


tensor([0.1984, 0.2933, 0.0895, 0.4188], device='cuda:7')


Epoch 126: 100%|██████████| 38/38 [00:10<00:00,  3.47batch/s, accuracy=96.61016949152543%, loss=0.245]


tensor([0.1984, 0.2920, 0.0896, 0.4200], device='cuda:7')


Epoch 127: 100%|██████████| 38/38 [00:10<00:00,  3.49batch/s, accuracy=94.91525423728814%, loss=0.244]


tensor([0.1985, 0.2904, 0.0895, 0.4215], device='cuda:7')


Epoch 128: 100%|██████████| 38/38 [00:10<00:00,  3.52batch/s, accuracy=96.61016949152543%, loss=0.186]


tensor([0.1995, 0.2888, 0.0891, 0.4226], device='cuda:7')


Epoch 129: 100%|██████████| 38/38 [00:10<00:00,  3.49batch/s, accuracy=96.61016949152543%, loss=0.238]


tensor([0.1997, 0.2880, 0.0889, 0.4234], device='cuda:7')


Epoch 130: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=89.83050847457628%, loss=0.247]


tensor([0.2005, 0.2879, 0.0884, 0.4232], device='cuda:7')


Epoch 131: 100%|██████████| 38/38 [00:10<00:00,  3.52batch/s, accuracy=89.83050847457628%, loss=0.259]


tensor([0.2004, 0.2874, 0.0879, 0.4243], device='cuda:7')


Epoch 132: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=89.83050847457628%, loss=0.297]


tensor([0.2011, 0.2872, 0.0875, 0.4242], device='cuda:7')


Epoch 133: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=96.61016949152543%, loss=0.221]


tensor([0.2011, 0.2860, 0.0877, 0.4252], device='cuda:7')


Epoch 134: 100%|██████████| 38/38 [00:10<00:00,  3.50batch/s, accuracy=93.22033898305085%, loss=0.225]


tensor([0.2010, 0.2854, 0.0872, 0.4264], device='cuda:7')


Epoch 135: 100%|██████████| 38/38 [00:10<00:00,  3.51batch/s, accuracy=98.30508474576271%, loss=0.185]


tensor([0.2014, 0.2841, 0.0872, 0.4273], device='cuda:7')


Epoch 136: 100%|██████████| 38/38 [00:10<00:00,  3.49batch/s, accuracy=98.30508474576271%, loss=0.165]


tensor([0.2019, 0.2837, 0.0870, 0.4275], device='cuda:7')


Epoch 137: 100%|██████████| 38/38 [00:11<00:00,  3.43batch/s, accuracy=98.30508474576271%, loss=0.17]


tensor([0.2022, 0.2837, 0.0867, 0.4274], device='cuda:7')


Epoch 138: 100%|██████████| 38/38 [00:11<00:00,  3.44batch/s, accuracy=96.61016949152543%, loss=0.211]


tensor([0.2027, 0.2821, 0.0868, 0.4285], device='cuda:7')


Epoch 139: 100%|██████████| 38/38 [00:10<00:00,  3.49batch/s, accuracy=98.30508474576271%, loss=0.201]


tensor([0.2030, 0.2809, 0.0868, 0.4293], device='cuda:7')


Epoch 140: 100%|██████████| 38/38 [00:10<00:00,  3.49batch/s, accuracy=98.30508474576271%, loss=0.201]


tensor([0.2024, 0.2796, 0.0873, 0.4307], device='cuda:7')


Epoch 141: 100%|██████████| 38/38 [00:10<00:00,  3.50batch/s, accuracy=96.61016949152543%, loss=0.212]


tensor([0.2039, 0.2800, 0.0870, 0.4291], device='cuda:7')


Epoch 142: 100%|██████████| 38/38 [00:11<00:00,  3.44batch/s, accuracy=96.61016949152543%, loss=0.231]


tensor([0.2047, 0.2795, 0.0870, 0.4288], device='cuda:7')


Epoch 143: 100%|██████████| 38/38 [00:10<00:00,  3.50batch/s, accuracy=96.61016949152543%, loss=0.192]


tensor([0.2055, 0.2783, 0.0871, 0.4291], device='cuda:7')


Epoch 144: 100%|██████████| 38/38 [00:10<00:00,  3.50batch/s, accuracy=94.91525423728814%, loss=0.254]


tensor([0.2065, 0.2780, 0.0867, 0.4288], device='cuda:7')


Epoch 145: 100%|██████████| 38/38 [00:10<00:00,  3.49batch/s, accuracy=93.22033898305085%, loss=0.23]


tensor([0.2070, 0.2769, 0.0871, 0.4290], device='cuda:7')


Epoch 146: 100%|██████████| 38/38 [00:10<00:00,  3.49batch/s, accuracy=96.61016949152543%, loss=0.19]


tensor([0.2081, 0.2776, 0.0870, 0.4273], device='cuda:7')


Epoch 147: 100%|██████████| 38/38 [00:10<00:00,  3.53batch/s, accuracy=100.0%, loss=0.181]   


tensor([0.2089, 0.2770, 0.0873, 0.4268], device='cuda:7')


Epoch 148: 100%|██████████| 38/38 [00:10<00:00,  3.50batch/s, accuracy=98.30508474576271%, loss=0.182]


tensor([0.2095, 0.2759, 0.0874, 0.4272], device='cuda:7')


Epoch 149: 100%|██████████| 38/38 [00:10<00:00,  3.49batch/s, accuracy=94.91525423728814%, loss=0.219]


tensor([0.2109, 0.2748, 0.0877, 0.4266], device='cuda:7')


Epoch 150: 100%|██████████| 38/38 [00:10<00:00,  3.49batch/s, accuracy=96.61016949152543%, loss=0.2]


tensor([0.2127, 0.2750, 0.0878, 0.4245], device='cuda:7')


Epoch 151: 100%|██████████| 38/38 [00:11<00:00,  3.45batch/s, accuracy=98.30508474576271%, loss=0.159]


tensor([0.2127, 0.2740, 0.0879, 0.4254], device='cuda:7')


Epoch 152: 100%|██████████| 38/38 [00:11<00:00,  3.45batch/s, accuracy=96.61016949152543%, loss=0.214]


tensor([0.2138, 0.2729, 0.0883, 0.4250], device='cuda:7')


Epoch 153: 100%|██████████| 38/38 [00:11<00:00,  3.45batch/s, accuracy=94.91525423728814%, loss=0.231]


tensor([0.2154, 0.2719, 0.0885, 0.4242], device='cuda:7')


Epoch 154: 100%|██████████| 38/38 [00:10<00:00,  3.52batch/s, accuracy=96.61016949152543%, loss=0.252]


tensor([0.2171, 0.2725, 0.0886, 0.4219], device='cuda:7')


Epoch 155: 100%|██████████| 38/38 [00:10<00:00,  3.51batch/s, accuracy=98.30508474576271%, loss=0.217]


tensor([0.2181, 0.2713, 0.0888, 0.4219], device='cuda:7')


Epoch 156: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=94.91525423728814%, loss=0.189]


tensor([0.2197, 0.2704, 0.0892, 0.4206], device='cuda:7')


Epoch 157: 100%|██████████| 38/38 [00:10<00:00,  3.51batch/s, accuracy=98.30508474576271%, loss=0.217]


tensor([0.2207, 0.2699, 0.0891, 0.4203], device='cuda:7')


Epoch 158: 100%|██████████| 38/38 [00:11<00:00,  3.45batch/s, accuracy=96.61016949152543%, loss=0.234]


tensor([0.2224, 0.2687, 0.0891, 0.4197], device='cuda:7')


Epoch 159: 100%|██████████| 38/38 [00:10<00:00,  3.46batch/s, accuracy=98.30508474576271%, loss=0.166]


tensor([0.2232, 0.2675, 0.0896, 0.4196], device='cuda:7')


Epoch 160: 100%|██████████| 38/38 [00:10<00:00,  3.50batch/s, accuracy=96.61016949152543%, loss=0.244]


tensor([0.2238, 0.2649, 0.0900, 0.4213], device='cuda:7')


Epoch 161: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=98.30508474576271%, loss=0.182]


tensor([0.2245, 0.2638, 0.0904, 0.4213], device='cuda:7')


Epoch 162: 100%|██████████| 38/38 [00:10<00:00,  3.47batch/s, accuracy=93.22033898305085%, loss=0.226]


tensor([0.2250, 0.2624, 0.0909, 0.4217], device='cuda:7')


Epoch 163: 100%|██████████| 38/38 [00:10<00:00,  3.51batch/s, accuracy=100.0%, loss=0.169]   


tensor([0.2261, 0.2610, 0.0920, 0.4209], device='cuda:7')


Epoch 164: 100%|██████████| 38/38 [00:10<00:00,  3.51batch/s, accuracy=100.0%, loss=0.16]    


tensor([0.2265, 0.2609, 0.0928, 0.4197], device='cuda:7')


Epoch 165: 100%|██████████| 38/38 [00:11<00:00,  3.45batch/s, accuracy=94.91525423728814%, loss=0.259]


tensor([0.2276, 0.2600, 0.0934, 0.4190], device='cuda:7')


Epoch 166: 100%|██████████| 38/38 [00:11<00:00,  3.45batch/s, accuracy=94.91525423728814%, loss=0.197]


tensor([0.2293, 0.2599, 0.0940, 0.4168], device='cuda:7')


Epoch 167: 100%|██████████| 38/38 [00:10<00:00,  3.51batch/s, accuracy=86.44067796610169%, loss=0.319]


tensor([0.2303, 0.2585, 0.0944, 0.4169], device='cuda:7')


Epoch 168: 100%|██████████| 38/38 [00:10<00:00,  3.49batch/s, accuracy=94.91525423728814%, loss=0.213]


tensor([0.2314, 0.2571, 0.0951, 0.4164], device='cuda:7')


Epoch 169: 100%|██████████| 38/38 [00:10<00:00,  3.50batch/s, accuracy=98.30508474576271%, loss=0.146]


tensor([0.2322, 0.2564, 0.0954, 0.4159], device='cuda:7')


Epoch 170: 100%|██████████| 38/38 [00:10<00:00,  3.51batch/s, accuracy=100.0%, loss=0.161]   


tensor([0.2330, 0.2563, 0.0961, 0.4146], device='cuda:7')


Epoch 171: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=98.30508474576271%, loss=0.219]


tensor([0.2342, 0.2550, 0.0968, 0.4140], device='cuda:7')


Epoch 172: 100%|██████████| 38/38 [00:10<00:00,  3.50batch/s, accuracy=96.61016949152543%, loss=0.14]


tensor([0.2354, 0.2550, 0.0974, 0.4122], device='cuda:7')


Epoch 173: 100%|██████████| 38/38 [00:11<00:00,  3.45batch/s, accuracy=98.30508474576271%, loss=0.162]


tensor([0.2364, 0.2539, 0.0984, 0.4113], device='cuda:7')


Epoch 174: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=98.30508474576271%, loss=0.183]


tensor([0.2372, 0.2529, 0.0990, 0.4108], device='cuda:7')


Epoch 175: 100%|██████████| 38/38 [00:11<00:00,  3.42batch/s, accuracy=96.61016949152543%, loss=0.205]


tensor([0.2383, 0.2518, 0.0999, 0.4100], device='cuda:7')


Epoch 176: 100%|██████████| 38/38 [00:11<00:00,  3.45batch/s, accuracy=94.91525423728814%, loss=0.233]


tensor([0.2389, 0.2510, 0.1006, 0.4094], device='cuda:7')


Epoch 177: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=98.30508474576271%, loss=0.196]


tensor([0.2390, 0.2492, 0.1018, 0.4100], device='cuda:7')


Epoch 178: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=100.0%, loss=0.155]   


tensor([0.2400, 0.2482, 0.1026, 0.4092], device='cuda:7')


Epoch 179: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=100.0%, loss=0.151]   


tensor([0.2397, 0.2464, 0.1035, 0.4104], device='cuda:7')


Epoch 180: 100%|██████████| 38/38 [00:10<00:00,  3.49batch/s, accuracy=94.91525423728814%, loss=0.19]


tensor([0.2413, 0.2467, 0.1044, 0.4075], device='cuda:7')


Epoch 181: 100%|██████████| 38/38 [00:10<00:00,  3.50batch/s, accuracy=100.0%, loss=0.186]   


tensor([0.2426, 0.2454, 0.1053, 0.4068], device='cuda:7')


Epoch 182: 100%|██████████| 38/38 [00:10<00:00,  3.47batch/s, accuracy=94.91525423728814%, loss=0.242]


tensor([0.2439, 0.2433, 0.1058, 0.4070], device='cuda:7')


Epoch 183: 100%|██████████| 38/38 [00:10<00:00,  3.47batch/s, accuracy=100.0%, loss=0.156]   


tensor([0.2449, 0.2427, 0.1070, 0.4054], device='cuda:7')


Epoch 184: 100%|██████████| 38/38 [00:10<00:00,  3.47batch/s, accuracy=91.52542372881356%, loss=0.225]


tensor([0.2459, 0.2416, 0.1081, 0.4044], device='cuda:7')


Epoch 185: 100%|██████████| 38/38 [00:10<00:00,  3.47batch/s, accuracy=94.91525423728814%, loss=0.189]


tensor([0.2469, 0.2409, 0.1096, 0.4026], device='cuda:7')


Epoch 186: 100%|██████████| 38/38 [00:10<00:00,  3.46batch/s, accuracy=94.91525423728814%, loss=0.185]


tensor([0.2484, 0.2397, 0.1105, 0.4014], device='cuda:7')


Epoch 187: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=100.0%, loss=0.138]   


tensor([0.2495, 0.2397, 0.1118, 0.3990], device='cuda:7')


Epoch 188: 100%|██████████| 38/38 [00:10<00:00,  3.50batch/s, accuracy=96.61016949152543%, loss=0.193]


tensor([0.2505, 0.2385, 0.1127, 0.3984], device='cuda:7')


Epoch 189: 100%|██████████| 38/38 [00:11<00:00,  3.43batch/s, accuracy=98.30508474576271%, loss=0.197]


tensor([0.2524, 0.2386, 0.1138, 0.3952], device='cuda:7')


Epoch 190: 100%|██████████| 38/38 [00:11<00:00,  3.45batch/s, accuracy=94.91525423728814%, loss=0.21]


tensor([0.2535, 0.2378, 0.1155, 0.3933], device='cuda:7')


Epoch 191: 100%|██████████| 38/38 [00:11<00:00,  3.44batch/s, accuracy=96.61016949152543%, loss=0.176]


tensor([0.2540, 0.2373, 0.1169, 0.3918], device='cuda:7')


Epoch 192: 100%|██████████| 38/38 [00:10<00:00,  3.46batch/s, accuracy=96.61016949152543%, loss=0.219]


tensor([0.2536, 0.2353, 0.1186, 0.3925], device='cuda:7')


Epoch 193: 100%|██████████| 38/38 [00:11<00:00,  3.45batch/s, accuracy=98.30508474576271%, loss=0.161]


tensor([0.2553, 0.2348, 0.1198, 0.3901], device='cuda:7')


Epoch 194: 100%|██████████| 38/38 [00:10<00:00,  3.49batch/s, accuracy=100.0%, loss=0.145]   


tensor([0.2565, 0.2335, 0.1213, 0.3887], device='cuda:7')


Epoch 195: 100%|██████████| 38/38 [00:10<00:00,  3.50batch/s, accuracy=94.91525423728814%, loss=0.199]


tensor([0.2569, 0.2319, 0.1228, 0.3884], device='cuda:7')


Epoch 196: 100%|██████████| 38/38 [00:10<00:00,  3.49batch/s, accuracy=100.0%, loss=0.149]   


tensor([0.2581, 0.2313, 0.1243, 0.3863], device='cuda:7')


Epoch 197: 100%|██████████| 38/38 [00:10<00:00,  3.49batch/s, accuracy=100.0%, loss=0.162]   


tensor([0.2589, 0.2309, 0.1255, 0.3847], device='cuda:7')


Epoch 198: 100%|██████████| 38/38 [00:10<00:00,  3.49batch/s, accuracy=98.30508474576271%, loss=0.167]


tensor([0.2595, 0.2300, 0.1269, 0.3835], device='cuda:7')


Epoch 199: 100%|██████████| 38/38 [00:10<00:00,  3.50batch/s, accuracy=100.0%, loss=0.133]   


tensor([0.2610, 0.2296, 0.1280, 0.3815], device='cuda:7')


Epoch 200: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=98.30508474576271%, loss=0.186]


tensor([0.2612, 0.2285, 0.1295, 0.3808], device='cuda:7')


Epoch 201: 100%|██████████| 38/38 [00:11<00:00,  3.43batch/s, accuracy=94.91525423728814%, loss=0.218]


tensor([0.2619, 0.2279, 0.1309, 0.3793], device='cuda:7')


Epoch 202: 100%|██████████| 38/38 [00:10<00:00,  3.47batch/s, accuracy=98.30508474576271%, loss=0.179]


tensor([0.2627, 0.2277, 0.1322, 0.3774], device='cuda:7')


Epoch 203: 100%|██████████| 38/38 [00:10<00:00,  3.46batch/s, accuracy=94.91525423728814%, loss=0.188]


tensor([0.2626, 0.2264, 0.1335, 0.3775], device='cuda:7')


Epoch 204: 100%|██████████| 38/38 [00:10<00:00,  3.50batch/s, accuracy=100.0%, loss=0.151]   


tensor([0.2635, 0.2250, 0.1353, 0.3762], device='cuda:7')


Epoch 205: 100%|██████████| 38/38 [00:10<00:00,  3.46batch/s, accuracy=96.61016949152543%, loss=0.21]


tensor([0.2644, 0.2245, 0.1370, 0.3741], device='cuda:7')


Epoch 206: 100%|██████████| 38/38 [00:10<00:00,  3.51batch/s, accuracy=100.0%, loss=0.191]   


tensor([0.2654, 0.2231, 0.1384, 0.3731], device='cuda:7')


Epoch 207: 100%|██████████| 38/38 [00:10<00:00,  3.47batch/s, accuracy=96.61016949152543%, loss=0.21]


tensor([0.2667, 0.2226, 0.1394, 0.3713], device='cuda:7')


Epoch 208: 100%|██████████| 38/38 [00:10<00:00,  3.46batch/s, accuracy=96.61016949152543%, loss=0.198]


tensor([0.2679, 0.2214, 0.1407, 0.3700], device='cuda:7')


Epoch 209: 100%|██████████| 38/38 [00:10<00:00,  3.47batch/s, accuracy=96.61016949152543%, loss=0.166]


tensor([0.2696, 0.2209, 0.1420, 0.3675], device='cuda:7')


Epoch 210: 100%|██████████| 38/38 [00:10<00:00,  3.49batch/s, accuracy=96.61016949152543%, loss=0.166]


tensor([0.2699, 0.2198, 0.1431, 0.3672], device='cuda:7')


Epoch 211: 100%|██████████| 38/38 [00:11<00:00,  3.42batch/s, accuracy=100.0%, loss=0.142]   


tensor([0.2713, 0.2188, 0.1445, 0.3654], device='cuda:7')


Epoch 212: 100%|██████████| 38/38 [00:10<00:00,  3.50batch/s, accuracy=96.61016949152543%, loss=0.206]


tensor([0.2723, 0.2184, 0.1457, 0.3636], device='cuda:7')


Epoch 213: 100%|██████████| 38/38 [00:11<00:00,  3.39batch/s, accuracy=98.30508474576271%, loss=0.148]


tensor([0.2726, 0.2176, 0.1470, 0.3627], device='cuda:7')


Epoch 214: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=100.0%, loss=0.162]   


tensor([0.2737, 0.2167, 0.1480, 0.3616], device='cuda:7')


Epoch 215: 100%|██████████| 38/38 [00:10<00:00,  3.49batch/s, accuracy=96.61016949152543%, loss=0.156]


tensor([0.2741, 0.2157, 0.1498, 0.3605], device='cuda:7')


Epoch 216: 100%|██████████| 38/38 [00:10<00:00,  3.46batch/s, accuracy=94.91525423728814%, loss=0.219]


tensor([0.2756, 0.2153, 0.1507, 0.3585], device='cuda:7')


Epoch 217: 100%|██████████| 38/38 [00:10<00:00,  3.50batch/s, accuracy=100.0%, loss=0.154]   


tensor([0.2771, 0.2156, 0.1520, 0.3554], device='cuda:7')


Epoch 218: 100%|██████████| 38/38 [00:10<00:00,  3.49batch/s, accuracy=96.61016949152543%, loss=0.183]


tensor([0.2778, 0.2152, 0.1533, 0.3538], device='cuda:7')


Epoch 219: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=96.61016949152543%, loss=0.174]


tensor([0.2791, 0.2147, 0.1541, 0.3521], device='cuda:7')


Epoch 220: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=98.30508474576271%, loss=0.151]


tensor([0.2802, 0.2141, 0.1553, 0.3504], device='cuda:7')


Epoch 221: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=98.30508474576271%, loss=0.165]


tensor([0.2814, 0.2131, 0.1560, 0.3496], device='cuda:7')


Epoch 222: 100%|██████████| 38/38 [00:10<00:00,  3.50batch/s, accuracy=94.91525423728814%, loss=0.206]


tensor([0.2825, 0.2125, 0.1570, 0.3480], device='cuda:7')


Epoch 223: 100%|██████████| 38/38 [00:10<00:00,  3.47batch/s, accuracy=98.30508474576271%, loss=0.158]


tensor([0.2829, 0.2119, 0.1583, 0.3470], device='cuda:7')


Epoch 224: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=94.91525423728814%, loss=0.195]


tensor([0.2841, 0.2120, 0.1588, 0.3451], device='cuda:7')


Epoch 225: 100%|██████████| 38/38 [00:10<00:00,  3.50batch/s, accuracy=94.91525423728814%, loss=0.216]


tensor([0.2848, 0.2111, 0.1600, 0.3440], device='cuda:7')


Epoch 226: 100%|██████████| 38/38 [00:10<00:00,  3.51batch/s, accuracy=98.30508474576271%, loss=0.191]


tensor([0.2848, 0.2104, 0.1616, 0.3432], device='cuda:7')


Epoch 227: 100%|██████████| 38/38 [00:10<00:00,  3.46batch/s, accuracy=98.30508474576271%, loss=0.151]


tensor([0.2857, 0.2099, 0.1628, 0.3416], device='cuda:7')


Epoch 228: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=96.61016949152543%, loss=0.197]


tensor([0.2860, 0.2095, 0.1641, 0.3404], device='cuda:7')


Epoch 229: 100%|██████████| 38/38 [00:11<00:00,  3.43batch/s, accuracy=96.61016949152543%, loss=0.224]


tensor([0.2863, 0.2086, 0.1646, 0.3405], device='cuda:7')


Epoch 230: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=93.22033898305085%, loss=0.23]


tensor([0.2862, 0.2076, 0.1665, 0.3397], device='cuda:7')


Epoch 231: 100%|██████████| 38/38 [00:10<00:00,  3.49batch/s, accuracy=100.0%, loss=0.173]   


tensor([0.2867, 0.2075, 0.1678, 0.3380], device='cuda:7')


Epoch 232: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=100.0%, loss=0.185]   


tensor([0.2875, 0.2067, 0.1691, 0.3367], device='cuda:7')


Epoch 233: 100%|██████████| 38/38 [00:10<00:00,  3.49batch/s, accuracy=98.30508474576271%, loss=0.168]


tensor([0.2876, 0.2061, 0.1705, 0.3358], device='cuda:7')


Epoch 234: 100%|██████████| 38/38 [00:10<00:00,  3.50batch/s, accuracy=96.61016949152543%, loss=0.187]


tensor([0.2875, 0.2051, 0.1717, 0.3356], device='cuda:7')


Epoch 235: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=98.30508474576271%, loss=0.156]


tensor([0.2883, 0.2048, 0.1728, 0.3341], device='cuda:7')


Epoch 236: 100%|██████████| 38/38 [00:10<00:00,  3.51batch/s, accuracy=100.0%, loss=0.153]   


tensor([0.2899, 0.2040, 0.1738, 0.3323], device='cuda:7')


Epoch 237: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=96.61016949152543%, loss=0.183]


tensor([0.2901, 0.2033, 0.1751, 0.3315], device='cuda:7')


Epoch 238: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=100.0%, loss=0.154]   


tensor([0.2912, 0.2026, 0.1759, 0.3303], device='cuda:7')


Epoch 239: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=98.30508474576271%, loss=0.175]


tensor([0.2912, 0.2027, 0.1775, 0.3285], device='cuda:7')


Epoch 240: 100%|██████████| 38/38 [00:11<00:00,  3.44batch/s, accuracy=100.0%, loss=0.163]   


tensor([0.2910, 0.2016, 0.1795, 0.3279], device='cuda:7')


Epoch 241: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=98.30508474576271%, loss=0.189]


tensor([0.2922, 0.2014, 0.1798, 0.3266], device='cuda:7')


Epoch 242: 100%|██████████| 38/38 [00:10<00:00,  3.52batch/s, accuracy=98.30508474576271%, loss=0.154]


tensor([0.2931, 0.2013, 0.1807, 0.3249], device='cuda:7')


Epoch 243: 100%|██████████| 38/38 [00:10<00:00,  3.53batch/s, accuracy=98.30508474576271%, loss=0.194]


tensor([0.2936, 0.2010, 0.1817, 0.3237], device='cuda:7')


Epoch 244: 100%|██████████| 38/38 [00:10<00:00,  3.47batch/s, accuracy=98.30508474576271%, loss=0.166]


tensor([0.2941, 0.2010, 0.1823, 0.3226], device='cuda:7')


Epoch 245: 100%|██████████| 38/38 [00:10<00:00,  3.49batch/s, accuracy=100.0%, loss=0.146]   


tensor([0.2953, 0.2008, 0.1828, 0.3211], device='cuda:7')


Epoch 246: 100%|██████████| 38/38 [00:10<00:00,  3.51batch/s, accuracy=96.61016949152543%, loss=0.191]


tensor([0.2952, 0.2005, 0.1839, 0.3204], device='cuda:7')


Epoch 247: 100%|██████████| 38/38 [00:10<00:00,  3.47batch/s, accuracy=98.30508474576271%, loss=0.184]


tensor([0.2953, 0.2002, 0.1848, 0.3197], device='cuda:7')


Epoch 248: 100%|██████████| 38/38 [00:10<00:00,  3.50batch/s, accuracy=100.0%, loss=0.158]   


tensor([0.2943, 0.1993, 0.1863, 0.3201], device='cuda:7')


Epoch 249: 100%|██████████| 38/38 [00:11<00:00,  3.44batch/s, accuracy=96.61016949152543%, loss=0.178]


tensor([0.2951, 0.1992, 0.1869, 0.3188], device='cuda:7')


Epoch 250: 100%|██████████| 38/38 [00:11<00:00,  3.43batch/s, accuracy=98.30508474576271%, loss=0.185]


tensor([0.2951, 0.1987, 0.1876, 0.3186], device='cuda:7')


Epoch 251: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=96.61016949152543%, loss=0.191]


tensor([0.2953, 0.1980, 0.1886, 0.3180], device='cuda:7')


Epoch 252: 100%|██████████| 38/38 [00:11<00:00,  3.44batch/s, accuracy=98.30508474576271%, loss=0.169]


tensor([0.2946, 0.1972, 0.1896, 0.3186], device='cuda:7')


Epoch 253: 100%|██████████| 38/38 [00:10<00:00,  3.49batch/s, accuracy=100.0%, loss=0.166]   


tensor([0.2946, 0.1967, 0.1902, 0.3185], device='cuda:7')


Epoch 254: 100%|██████████| 38/38 [00:10<00:00,  3.47batch/s, accuracy=100.0%, loss=0.155]   


tensor([0.2947, 0.1967, 0.1906, 0.3180], device='cuda:7')


Epoch 255: 100%|██████████| 38/38 [00:10<00:00,  3.49batch/s, accuracy=100.0%, loss=0.168]   


tensor([0.2962, 0.1966, 0.1910, 0.3161], device='cuda:7')


Epoch 256: 100%|██████████| 38/38 [00:10<00:00,  3.51batch/s, accuracy=96.61016949152543%, loss=0.177]


tensor([0.2970, 0.1965, 0.1918, 0.3147], device='cuda:7')


Epoch 257: 100%|██████████| 38/38 [00:10<00:00,  3.51batch/s, accuracy=98.30508474576271%, loss=0.18]


tensor([0.2973, 0.1963, 0.1920, 0.3144], device='cuda:7')


Epoch 258: 100%|██████████| 38/38 [00:10<00:00,  3.50batch/s, accuracy=100.0%, loss=0.159]   


tensor([0.2965, 0.1961, 0.1930, 0.3143], device='cuda:7')


Epoch 259: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=100.0%, loss=0.16]    


tensor([0.2972, 0.1960, 0.1930, 0.3138], device='cuda:7')


Epoch 260: 100%|██████████| 38/38 [00:10<00:00,  3.47batch/s, accuracy=100.0%, loss=0.163]   


tensor([0.2977, 0.1955, 0.1941, 0.3128], device='cuda:7')


Epoch 261: 100%|██████████| 38/38 [00:10<00:00,  3.50batch/s, accuracy=98.30508474576271%, loss=0.184]


tensor([0.2967, 0.1947, 0.1947, 0.3138], device='cuda:7')


Epoch 262: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=96.61016949152543%, loss=0.202]


tensor([0.2971, 0.1944, 0.1953, 0.3132], device='cuda:7')


Epoch 263: 100%|██████████| 38/38 [00:10<00:00,  3.49batch/s, accuracy=98.30508474576271%, loss=0.167]


tensor([0.2978, 0.1942, 0.1957, 0.3123], device='cuda:7')


Epoch 264: 100%|██████████| 38/38 [00:10<00:00,  3.50batch/s, accuracy=98.30508474576271%, loss=0.17]


tensor([0.2981, 0.1941, 0.1963, 0.3114], device='cuda:7')


Epoch 265: 100%|██████████| 38/38 [00:10<00:00,  3.51batch/s, accuracy=98.30508474576271%, loss=0.163]


tensor([0.2976, 0.1936, 0.1971, 0.3116], device='cuda:7')


Epoch 266: 100%|██████████| 38/38 [00:11<00:00,  3.44batch/s, accuracy=100.0%, loss=0.172]   


tensor([0.2972, 0.1936, 0.1978, 0.3114], device='cuda:7')


Epoch 267: 100%|██████████| 38/38 [00:10<00:00,  3.46batch/s, accuracy=96.61016949152543%, loss=0.191]


tensor([0.2968, 0.1932, 0.1978, 0.3123], device='cuda:7')


Epoch 268: 100%|██████████| 38/38 [00:10<00:00,  3.50batch/s, accuracy=100.0%, loss=0.16]    


tensor([0.2966, 0.1933, 0.1982, 0.3120], device='cuda:7')


Epoch 269: 100%|██████████| 38/38 [00:10<00:00,  3.50batch/s, accuracy=98.30508474576271%, loss=0.194]


tensor([0.2978, 0.1938, 0.1976, 0.3108], device='cuda:7')


Epoch 270: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=100.0%, loss=0.169]   


tensor([0.2986, 0.1941, 0.1974, 0.3099], device='cuda:7')


Epoch 271: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=100.0%, loss=0.181]   


tensor([0.2996, 0.1952, 0.1968, 0.3085], device='cuda:7')


Epoch 272: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=100.0%, loss=0.182]   


tensor([0.2990, 0.1952, 0.1972, 0.3086], device='cuda:7')


Epoch 273: 100%|██████████| 38/38 [00:10<00:00,  3.49batch/s, accuracy=98.30508474576271%, loss=0.177]


tensor([0.2991, 0.1951, 0.1971, 0.3088], device='cuda:7')


Epoch 274: 100%|██████████| 38/38 [00:10<00:00,  3.51batch/s, accuracy=96.61016949152543%, loss=0.218]


tensor([0.2985, 0.1953, 0.1968, 0.3095], device='cuda:7')


Epoch 275: 100%|██████████| 38/38 [00:10<00:00,  3.54batch/s, accuracy=100.0%, loss=0.17]    


tensor([0.2981, 0.1962, 0.1972, 0.3085], device='cuda:7')


Epoch 276: 100%|██████████| 38/38 [00:10<00:00,  3.50batch/s, accuracy=94.91525423728814%, loss=0.236]


tensor([0.2979, 0.1964, 0.1970, 0.3087], device='cuda:7')


Epoch 277: 100%|██████████| 38/38 [00:10<00:00,  3.50batch/s, accuracy=100.0%, loss=0.161]   


tensor([0.2983, 0.1968, 0.1971, 0.3078], device='cuda:7')


Epoch 278: 100%|██████████| 38/38 [00:10<00:00,  3.49batch/s, accuracy=100.0%, loss=0.171]   


tensor([0.2992, 0.1975, 0.1967, 0.3066], device='cuda:7')


Epoch 279: 100%|██████████| 38/38 [00:10<00:00,  3.51batch/s, accuracy=100.0%, loss=0.172]   


tensor([0.2981, 0.1978, 0.1973, 0.3068], device='cuda:7')


Epoch 280: 100%|██████████| 38/38 [00:10<00:00,  3.50batch/s, accuracy=96.61016949152543%, loss=0.198]


tensor([0.2983, 0.1979, 0.1975, 0.3063], device='cuda:7')


Epoch 281: 100%|██████████| 38/38 [00:10<00:00,  3.51batch/s, accuracy=100.0%, loss=0.172]   


tensor([0.2980, 0.1980, 0.1979, 0.3061], device='cuda:7')


Epoch 282: 100%|██████████| 38/38 [00:10<00:00,  3.49batch/s, accuracy=98.30508474576271%, loss=0.174]


tensor([0.2980, 0.1981, 0.1975, 0.3064], device='cuda:7')


Epoch 283: 100%|██████████| 38/38 [00:10<00:00,  3.49batch/s, accuracy=98.30508474576271%, loss=0.182]


tensor([0.2980, 0.1986, 0.1976, 0.3058], device='cuda:7')


Epoch 284: 100%|██████████| 38/38 [00:10<00:00,  3.49batch/s, accuracy=100.0%, loss=0.174]   


tensor([0.2976, 0.1986, 0.1975, 0.3063], device='cuda:7')


Epoch 285: 100%|██████████| 38/38 [00:10<00:00,  3.52batch/s, accuracy=100.0%, loss=0.169]   


tensor([0.2972, 0.1987, 0.1972, 0.3068], device='cuda:7')


Epoch 286: 100%|██████████| 38/38 [00:10<00:00,  3.50batch/s, accuracy=98.30508474576271%, loss=0.199]


tensor([0.2970, 0.1993, 0.1970, 0.3068], device='cuda:7')


Epoch 287: 100%|██████████| 38/38 [00:11<00:00,  3.45batch/s, accuracy=100.0%, loss=0.165]   


tensor([0.2973, 0.1998, 0.1970, 0.3059], device='cuda:7')


Epoch 288: 100%|██████████| 38/38 [00:11<00:00,  3.44batch/s, accuracy=100.0%, loss=0.178]   


tensor([0.2966, 0.2001, 0.1971, 0.3062], device='cuda:7')


Epoch 289: 100%|██████████| 38/38 [00:10<00:00,  3.49batch/s, accuracy=100.0%, loss=0.171]   


tensor([0.2969, 0.2010, 0.1967, 0.3053], device='cuda:7')


Epoch 290: 100%|██████████| 38/38 [00:11<00:00,  3.36batch/s, accuracy=100.0%, loss=0.158]   


tensor([0.2975, 0.2019, 0.1961, 0.3045], device='cuda:7')


Epoch 291: 100%|██████████| 38/38 [00:10<00:00,  3.52batch/s, accuracy=96.61016949152543%, loss=0.185]


tensor([0.2970, 0.2023, 0.1963, 0.3044], device='cuda:7')


Epoch 292: 100%|██████████| 38/38 [00:10<00:00,  3.51batch/s, accuracy=100.0%, loss=0.151]   


tensor([0.2959, 0.2024, 0.1969, 0.3048], device='cuda:7')


Epoch 293: 100%|██████████| 38/38 [00:10<00:00,  3.54batch/s, accuracy=100.0%, loss=0.178]   


tensor([0.2954, 0.2030, 0.1970, 0.3046], device='cuda:7')


Epoch 294: 100%|██████████| 38/38 [00:10<00:00,  3.48batch/s, accuracy=96.61016949152543%, loss=0.188]


tensor([0.2962, 0.2035, 0.1967, 0.3037], device='cuda:7')


Epoch 295: 100%|██████████| 38/38 [00:10<00:00,  3.49batch/s, accuracy=100.0%, loss=0.165]   


tensor([0.2961, 0.2040, 0.1967, 0.3033], device='cuda:7')


Epoch 296: 100%|██████████| 38/38 [00:10<00:00,  3.49batch/s, accuracy=98.30508474576271%, loss=0.185]


tensor([0.2967, 0.2046, 0.1959, 0.3029], device='cuda:7')


Epoch 297: 100%|██████████| 38/38 [00:10<00:00,  3.52batch/s, accuracy=100.0%, loss=0.165]   


tensor([0.2962, 0.2048, 0.1958, 0.3033], device='cuda:7')


Epoch 298: 100%|██████████| 38/38 [00:10<00:00,  3.53batch/s, accuracy=98.30508474576271%, loss=0.198]


tensor([0.2957, 0.2049, 0.1961, 0.3034], device='cuda:7')


Epoch 299: 100%|██████████| 38/38 [00:10<00:00,  3.47batch/s, accuracy=100.0%, loss=0.18]    

tensor([0.2948, 0.2050, 0.1962, 0.3040], device='cuda:7')


In [9]:
from spuco.evaluate import Evaluator

evaluator = Evaluator(
    testset=testset,
    group_partition=testset.group_partition,
    group_weights=trainset.group_weights,
    batch_size=64,
    model=model,
    device=device,
    verbose=True
)
evaluator.evaluate()

Evaluating group-wise accuracy:  25%|██▌       | 1/4 [00:02<00:08,  2.74s/it]

Group (0, 0) Test Accuracy: 98.22616407982261


Evaluating group-wise accuracy:  50%|█████     | 2/4 [00:05<00:05,  2.64s/it]

Group (0, 1) Test Accuracy: 89.490022172949


Evaluating group-wise accuracy:  75%|███████▌  | 3/4 [00:06<00:02,  2.05s/it]

Group (1, 0) Test Accuracy: 85.202492211838


Evaluating group-wise accuracy: 100%|██████████| 4/4 [00:07<00:00,  1.98s/it]

Group (1, 1) Test Accuracy: 92.05607476635514


{(0, 0): 98.22616407982261,
 (0, 1): 89.490022172949,
 (1, 0): 85.202492211838,
 (1, 1): 92.05607476635514}