In [1]:
%pip install ../../../

Processing /home/sjoshi/spuco
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
  Created wheel for spuco: filename=spuco-0.0.1-py3-none-any.whl size=68585 sha256=fa53067eb718c08bed9919e55cbc17d83de72e69291a31deb339550e7ad56e00
  Stored in directory: /tmp/pip-ephem-wheel-cache-uz5i0cor/wheels/ef/5d/43/a265894b1d52121a51705a208277e8d9a9670e95fa1a2e7ae6
Successfully built spuco
  Attempting uninstall: spuco
    Found existing installation: spuco 0.0.1
    Uninstalling spuco-0.0.1:
      Successfully uninstalled spuco-0.0.1
Note: you may need to restart the kernel to use updated packages.


In [2]:
import torch 

device = torch.device("cuda:7")

In [3]:
from spuco.datasets import SpuCoMNIST, SpuriousFeatureDifficulty
import torchvision.transforms as T

classes = [[0, 1], [2, 3], [4, 5], [6, 7], [8, 9]]
difficulty = SpuriousFeatureDifficulty.MAGNITUDE_EASY
transform = T.Compose([T.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])

trainset = SpuCoMNIST(
    root="/data/mnist/",
    spurious_feature_difficulty=difficulty,
    spurious_correlation_strength=0.99,
    classes=classes,
    split="train",
    transform=transform
)
trainset.initialize()

testset = SpuCoMNIST(
    root="/data/mnist/",
    spurious_feature_difficulty=difficulty,
    classes=classes,
    split="test",
    transform=transform
)
testset.initialize()

In [4]:
from spuco.models import model_factory 
from torch.optim import SGD
from spuco.end2end import LFF

bias_model=model_factory("lenet", trainset[0][0].shape, len(classes)).to(device)
model=model_factory("lenet", trainset[0][0].shape, len(classes)).to(device)
lff = LFF(
    trainset=trainset,
    bias_model=bias_model,
    debias_model=model,
    batch_size=4,
    bias_optimizer=SGD(bias_model.parameters(), lr=1e-3, weight_decay=5e-4),
    debias_optimizer=SGD(model.parameters(), lr=1e-3, weight_decay=5e-4),
    q=0.2,
    num_epochs=1,
    device=device,
    verbose=True
)
lff.train()

Epoch 0:   0%|          | 0/12001 [00:00<?, ?batch/s]

tensor([[-0.0383, -0.0377, -0.0231, -0.0357, -0.0251],
        [-0.0436, -0.0405, -0.0321, -0.0108, -0.0496],
        [-0.0220, -0.0245, -0.0208, -0.0486, -0.0208],
        [-0.0315, -0.0343, -0.0367, -0.0441, -0.0182]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2489, 0.2491, 0.2513, 0.2498, 0.2508],
        [0.2476, 0.2484, 0.2490, 0.2560, 0.2447],
        [0.2530, 0.2524, 0.2518, 0.2465, 0.2519],
        [0.2506, 0.2500, 0.2479, 0.2477, 0.2526]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7584, 0.7573, 0.7596, 0.7594], device='cuda:7', dtype=torch.float64)


Epoch 0:   0%|          | 9/12001 [00:01<21:48,  9.16batch/s, bias_accuracy=25.0%, bias_loss=1.22, debias_accuracy=25.0%, debias_loss=0.806]  

tensor([[-4.6636e-02, -3.8617e-02, -2.9326e-02, -1.3396e-02, -2.8130e-02],
        [-3.5797e-02, -4.6069e-02, -8.5978e-05, -1.8320e-02, -2.6016e-02],
        [-2.2753e-02, -2.8907e-02, -2.5706e-02, -2.4391e-02, -2.4244e-02],
        [-4.1555e-02, -3.1764e-02, -3.1684e-02, -2.9457e-02, -1.6896e-02]],
       device='cuda:7', grad_fn=<AddmmBackward0>)
tensor([[0.2475, 0.2494, 0.2481, 0.2520, 0.2489],
        [0.2502, 0.2476, 0.2554, 0.2508, 0.2494],
        [0.2535, 0.2519, 0.2490, 0.2492, 0.2499],
        [0.2488, 0.2511, 0.2475, 0.2480, 0.2517]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7567, 0.7564, 0.7578, 0.7589], device='cuda:7', dtype=torch.float64)
tensor([[-0.0389, -0.0380, -0.0403, -0.0203, -0.0351],
        [-0.0456, -0.0408, -0.0339, -0.0229, -0.0329],
        [-0.0511, -0.0437, -0.0028, -0.0315, -0.0191],
        [-0.0447, -0.0384, -0.0330, -0.0106, -0.0381]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2516, 0.2506, 0.2468, 0.2502, 0.249

Epoch 0:   0%|          | 28/12001 [00:01<06:16, 31.84batch/s, bias_accuracy=75.0%, bias_loss=1.21, debias_accuracy=0.0%, debias_loss=0.808] 

tensor([[-0.0297, -0.0287, -0.0114, -0.0171, -0.0316],
        [-0.0406, -0.0283, -0.0239, -0.0262, -0.0341],
        [-0.0192, -0.0243, -0.0283, -0.0366, -0.0180],
        [-0.0274, -0.0352, -0.0324, -0.0197, -0.0267]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2499, 0.2501, 0.2532, 0.2520, 0.2490],
        [0.2472, 0.2502, 0.2500, 0.2497, 0.2484],
        [0.2525, 0.2512, 0.2489, 0.2471, 0.2524],
        [0.2505, 0.2485, 0.2479, 0.2513, 0.2502]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7572, 0.7580, 0.7594, 0.7580], device='cuda:7', dtype=torch.float64)
tensor([[-0.0290, -0.0423, -0.0264, -0.0323, -0.0302],
        [-0.0501, -0.0338, -0.0238, -0.0174, -0.0362],
        [-0.0455, -0.0380, -0.0187, -0.0276, -0.0293],
        [-0.0395, -0.0403, -0.0142, -0.0270, -0.0383]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2530, 0.2491, 0.2486, 0.2484, 0.2508],
        [0.2477, 0.2512, 0.2492, 0.2522, 0.2493],
        [0.2489, 0.2501, 0

Epoch 0:   0%|          | 48/12001 [00:01<03:39, 54.55batch/s, bias_accuracy=25.0%, bias_loss=1.22, debias_accuracy=0.0%, debias_loss=0.805] 

tensor([[-0.0288, -0.0381, -0.0293, -0.0418, -0.0182],
        [-0.0394, -0.0369, -0.0189, -0.0248, -0.0323],
        [-0.0378, -0.0441, -0.0326, -0.0181, -0.0171],
        [-0.0515, -0.0437, -0.0191, -0.0159, -0.0318]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2526, 0.2507, 0.2489, 0.2459, 0.2517],
        [0.2500, 0.2509, 0.2515, 0.2501, 0.2481],
        [0.2504, 0.2491, 0.2481, 0.2518, 0.2519],
        [0.2470, 0.2493, 0.2515, 0.2523, 0.2483]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7589, 0.7584, 0.7589, 0.7587], device='cuda:7', dtype=torch.float64)
tensor([[-0.0351, -0.0372, -0.0298, -0.0417, -0.0283],
        [-0.0315, -0.0365, -0.0142, -0.0213, -0.0221],
        [-0.0375, -0.0378, -0.0136, -0.0180, -0.0229],
        [-0.0414, -0.0415, -0.0027, -0.0298, -0.0304]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2503, 0.2502, 0.2463, 0.2465, 0.2494],
        [0.2512, 0.2504, 0.2502, 0.2516, 0.2510],
        [0.2497, 0.2501, 0

Epoch 0:   1%|          | 68/12001 [00:02<02:44, 72.54batch/s, bias_accuracy=0.0%, bias_loss=1.22, debias_accuracy=25.0%, debias_loss=0.808] 

tensor([[-0.0406, -0.0282, -0.0260, -0.0176, -0.0317],
        [-0.0470, -0.0362, -0.0264, -0.0177, -0.0366],
        [-0.0427, -0.0404, -0.0159, -0.0351, -0.0212],
        [-0.0324, -0.0359,  0.0011, -0.0258, -0.0385]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2500, 0.2517, 0.2477, 0.2516, 0.2501],
        [0.2484, 0.2497, 0.2476, 0.2516, 0.2488],
        [0.2495, 0.2487, 0.2502, 0.2472, 0.2527],
        [0.2521, 0.2498, 0.2545, 0.2496, 0.2484]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7589, 0.7564, 0.7595, 0.7577], device='cuda:7', dtype=torch.float64)
tensor([[-0.0492, -0.0522, -0.0248, -0.0104, -0.0288],
        [-0.0363, -0.0303, -0.0097, -0.0215, -0.0420],
        [-0.0410, -0.0367, -0.0246, -0.0221, -0.0341],
        [-0.0335, -0.0298, -0.0160, -0.0261, -0.0309]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2477, 0.2463, 0.2485, 0.2524, 0.2513],
        [0.2509, 0.2517, 0.2523, 0.2496, 0.2480],
        [0.2497, 0.2501, 0

Epoch 0:   1%|          | 89/12001 [00:02<02:23, 82.81batch/s, bias_accuracy=25.0%, bias_loss=1.22, debias_accuracy=0.0%, debias_loss=0.809] 

tensor([[-0.0443, -0.0415, -0.0405, -0.0148, -0.0240],
        [-0.0281, -0.0347, -0.0380, -0.0521, -0.0016],
        [-0.0222, -0.0170, -0.0199, -0.0423, -0.0143],
        [-0.0358, -0.0285, -0.0264, -0.0157, -0.0307]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2471, 0.2472, 0.2477, 0.2541, 0.2484],
        [0.2511, 0.2489, 0.2483, 0.2448, 0.2540],
        [0.2526, 0.2534, 0.2528, 0.2472, 0.2508],
        [0.2492, 0.2505, 0.2512, 0.2539, 0.2467]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7603, 0.7603, 0.7594, 0.7581], device='cuda:7', dtype=torch.float64)
tensor([[-0.0501, -0.0386, -0.0216, -0.0271, -0.0391],
        [-0.0320, -0.0317, -0.0186, -0.0512, -0.0202],
        [-0.0475, -0.0451, -0.0199, -0.0245, -0.0260],
        [-0.0345, -0.0389, -0.0234, -0.0119, -0.0333]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2477, 0.2500, 0.2498, 0.2504, 0.2476],
        [0.2523, 0.2517, 0.2506, 0.2444, 0.2524],
        [0.2484, 0.2484, 0

Epoch 0:   1%|          | 110/12001 [00:02<02:13, 89.12batch/s, bias_accuracy=25.0%, bias_loss=1.22, debias_accuracy=25.0%, debias_loss=0.795]

tensor([[-0.0587, -0.0503, -0.0224, -0.0174, -0.0308],
        [-0.0488, -0.0339, -0.0172, -0.0247, -0.0323],
        [-0.0283, -0.0256, -0.0214, -0.0502, -0.0170],
        [-0.0547, -0.0381, -0.0347, -0.0200, -0.0285]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2472, 0.2467, 0.2504, 0.2527, 0.2491],
        [0.2497, 0.2508, 0.2517, 0.2508, 0.2487],
        [0.2549, 0.2529, 0.2506, 0.2445, 0.2526],
        [0.2482, 0.2497, 0.2473, 0.2520, 0.2497]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7595, 0.7589, 0.7608, 0.7562], device='cuda:7', dtype=torch.float64)
tensor([[-0.0422, -0.0357, -0.0138, -0.0346, -0.0317],
        [-0.0294, -0.0178, -0.0287, -0.0253, -0.0245],
        [-0.0361, -0.0366, -0.0333, -0.0503, -0.0039],
        [-0.0410, -0.0361, -0.0407, -0.0281, -0.0202]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2487, 0.2490, 0.2538, 0.2500, 0.2471],
        [0.2520, 0.2534, 0.2501, 0.2523, 0.2489],
        [0.2503, 0.2487, 0

Epoch 0:   1%|          | 130/12001 [00:02<02:06, 93.69batch/s, bias_accuracy=0.0%, bias_loss=1.22, debias_accuracy=0.0%, debias_loss=0.809]  

tensor([[-0.0388, -0.0508, -0.0297, -0.0435, -0.0077],
        [-0.0613, -0.0679, -0.0063, -0.0276, -0.0192],
        [-0.0609, -0.0393, -0.0303, -0.0216, -0.0329],
        [-0.0578, -0.0322, -0.0342, -0.0103, -0.0347]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2540, 0.2492, 0.2489, 0.2456, 0.2540],
        [0.2483, 0.2449, 0.2547, 0.2495, 0.2511],
        [0.2485, 0.2521, 0.2487, 0.2510, 0.2477],
        [0.2492, 0.2538, 0.2477, 0.2539, 0.2472]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7603, 0.7576, 0.7571, 0.7602], device='cuda:7', dtype=torch.float64)
tensor([[-0.0217, -0.0270, -0.0141, -0.0503, -0.0070],
        [-0.0353, -0.0286, -0.0234, -0.0178, -0.0287],
        [-0.0555, -0.0498, -0.0194, -0.0019, -0.0377],
        [-0.0335, -0.0339, -0.0125, -0.0289, -0.0283]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2537, 0.2520, 0.2508, 0.2437, 0.2546],
        [0.2503, 0.2515, 0.2485, 0.2517, 0.2492],
        [0.2453, 0.2463, 0

Epoch 0:   1%|          | 150/12001 [00:02<02:05, 94.39batch/s, bias_accuracy=50.0%, bias_loss=1.21, debias_accuracy=0.0%, debias_loss=0.81]  

tensor([[-0.0318, -0.0313, -0.0353, -0.0204, -0.0275],
        [-0.0416, -0.0376, -0.0383, -0.0100, -0.0305],
        [-0.0302, -0.0231, -0.0387, -0.0360, -0.0165],
        [-0.0178, -0.0233, -0.0174, -0.0458, -0.0215]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2496, 0.2494, 0.2493, 0.2519, 0.2491],
        [0.2472, 0.2478, 0.2485, 0.2545, 0.2484],
        [0.2500, 0.2514, 0.2484, 0.2480, 0.2519],
        [0.2532, 0.2514, 0.2538, 0.2456, 0.2506]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7573, 0.7570, 0.7590, 0.7598], device='cuda:7', dtype=torch.float64)
tensor([[-0.0383, -0.0375, -0.0297, -0.0325, -0.0139],
        [-0.0431, -0.0374, -0.0296, -0.0165, -0.0257],
        [-0.0295, -0.0429, -0.0314,  0.0025, -0.0311],
        [-0.0623, -0.0418, -0.0110, -0.0231, -0.0373]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2512, 0.2506, 0.2489, 0.2462, 0.2533],
        [0.2500, 0.2506, 0.2490, 0.2502, 0.2503],
        [0.2534, 0.2493, 0

Epoch 0:   1%|▏         | 171/12001 [00:03<02:02, 96.50batch/s, bias_accuracy=75.0%, bias_loss=1.21, debias_accuracy=0.0%, debias_loss=0.802] 

tensor([[0.2493, 0.2497, 0.2501, 0.2555, 0.2477],
        [0.2521, 0.2535, 0.2482, 0.2466, 0.2502],
        [0.2516, 0.2494, 0.2513, 0.2491, 0.2486],
        [0.2470, 0.2475, 0.2505, 0.2488, 0.2535]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7577, 0.7591, 0.7588, 0.7599], device='cuda:7', dtype=torch.float64)
tensor([[-0.0267, -0.0202, -0.0277, -0.0512, -0.0109],
        [-0.0352, -0.0528, -0.0390, -0.0278, -0.0195],
        [-0.0482, -0.0343, -0.0304, -0.0055, -0.0386],
        [-0.0441, -0.0470, -0.0383, -0.0155, -0.0188]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2530, 0.2546, 0.2515, 0.2435, 0.2528],
        [0.2508, 0.2465, 0.2487, 0.2493, 0.2506],
        [0.2476, 0.2510, 0.2509, 0.2549, 0.2459],
        [0.2486, 0.2479, 0.2489, 0.2524, 0.2508]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7597, 0.7582, 0.7584, 0.7572], device='cuda:7', dtype=torch.float64)
tensor([[-0.0586, -0.0477, -0.0173, -0.0211, -0.0255],
        [-

Epoch 0:   2%|▏         | 191/12001 [00:03<02:01, 96.88batch/s, bias_accuracy=0.0%, bias_loss=1.22, debias_accuracy=0.0%, debias_loss=0.812]  

tensor([[0.2530, 0.2544, 0.2529, 0.2457, 0.2502],
        [0.2469, 0.2455, 0.2480, 0.2543, 0.2474],
        [0.2506, 0.2487, 0.2482, 0.2492, 0.2546],
        [0.2495, 0.2514, 0.2509, 0.2508, 0.2477]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7597, 0.7604, 0.7607, 0.7587], device='cuda:7', dtype=torch.float64)
tensor([[-0.0148, -0.0216, -0.0242, -0.0548, -0.0164],
        [-0.0468, -0.0488, -0.0346,  0.0035, -0.0220],
        [-0.0118, -0.0248, -0.0238, -0.0421, -0.0181],
        [-0.0584, -0.0430, -0.0074, -0.0182, -0.0287]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2545, 0.2532, 0.2496, 0.2433, 0.2512],
        [0.2465, 0.2465, 0.2470, 0.2579, 0.2498],
        [0.2553, 0.2524, 0.2497, 0.2464, 0.2508],
        [0.2437, 0.2479, 0.2538, 0.2524, 0.2482]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7606, 0.7626, 0.7610, 0.7593], device='cuda:7', dtype=torch.float64)
tensor([[-0.0430, -0.0297, -0.0167, -0.0247, -0.0337],
        [-

Epoch 0:   2%|▏         | 211/12001 [00:03<02:01, 96.76batch/s, bias_accuracy=50.0%, bias_loss=1.21, debias_accuracy=50.0%, debias_loss=0.802] 

tensor([[-0.0521, -0.0475, -0.0133,  0.0019, -0.0291],
        [-0.0207, -0.0300, -0.0254, -0.0568, -0.0121],
        [-0.0518, -0.0427, -0.0334, -0.0157, -0.0262],
        [-0.0500, -0.0446, -0.0232, -0.0217, -0.0420]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2479, 0.2484, 0.2526, 0.2563, 0.2495],
        [0.2558, 0.2528, 0.2496, 0.2416, 0.2538],
        [0.2479, 0.2496, 0.2476, 0.2518, 0.2503],
        [0.2484, 0.2491, 0.2502, 0.2503, 0.2464]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7595, 0.7613, 0.7564, 0.7579], device='cuda:7', dtype=torch.float64)
tensor([[-0.0205, -0.0238, -0.0225, -0.0468, -0.0177],
        [-0.0395, -0.0313, -0.0100, -0.0325, -0.0377],
        [-0.0355, -0.0366, -0.0082, -0.0297, -0.0392],
        [-0.0244, -0.0372, -0.0309, -0.0178, -0.0260]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2524, 0.2521, 0.2489, 0.2462, 0.2531],
        [0.2476, 0.2502, 0.2520, 0.2498, 0.2481],
        [0.2486, 0.2489, 0

Epoch 0:   2%|▏         | 232/12001 [00:03<01:59, 98.78batch/s, bias_accuracy=50.0%, bias_loss=1.21, debias_accuracy=25.0%, debias_loss=0.802]

tensor([[-0.0168, -0.0235, -0.0300, -0.0489, -0.0147],
        [-0.0397, -0.0366, -0.0321, -0.0084, -0.0336],
        [-0.0347, -0.0295, -0.0238, -0.0213, -0.0328],
        [-0.0563, -0.0380, -0.0096, -0.0138, -0.0425]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2550, 0.2521, 0.2485, 0.2436, 0.2541],
        [0.2493, 0.2488, 0.2480, 0.2537, 0.2493],
        [0.2505, 0.2506, 0.2500, 0.2504, 0.2495],
        [0.2452, 0.2485, 0.2536, 0.2523, 0.2471]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7609, 0.7566, 0.7582, 0.7600], device='cuda:7', dtype=torch.float64)
tensor([[-0.0478, -0.0468, -0.0135,  0.0006, -0.0436],
        [-0.0091, -0.0146, -0.0247, -0.0494, -0.0181],
        [-0.0429, -0.0406, -0.0295, -0.0061, -0.0167],
        [-0.0440, -0.0424, -0.0130, -0.0147, -0.0519]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2470, 0.2473, 0.2517, 0.2545, 0.2472],
        [0.2568, 0.2554, 0.2489, 0.2421, 0.2536],
        [0.2482, 0.2489, 0

Epoch 0:   2%|▏         | 253/12001 [00:03<01:59, 98.29batch/s, bias_accuracy=75.0%, bias_loss=1.2, debias_accuracy=25.0%, debias_loss=0.791] 

tensor([[-0.0295, -0.0320, -0.0325, -0.0175, -0.0321],
        [-0.0408, -0.0338, -0.0143, -0.0325, -0.0191],
        [-0.0460, -0.0343, -0.0223, -0.0210, -0.0383],
        [-0.0501, -0.0452, -0.0231, -0.0153, -0.0380]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2530, 0.2511, 0.2477, 0.2510, 0.2499],
        [0.2502, 0.2506, 0.2522, 0.2473, 0.2532],
        [0.2489, 0.2505, 0.2502, 0.2501, 0.2484],
        [0.2479, 0.2478, 0.2500, 0.2516, 0.2485]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7578, 0.7582, 0.7582, 0.7578], device='cuda:7', dtype=torch.float64)
tensor([[-0.0334, -0.0429, -0.0416, -0.0284, -0.0105],
        [-0.0594, -0.0436, -0.0177, -0.0157, -0.0422],
        [-0.0077, -0.0191, -0.0240, -0.0529, -0.0179],
        [-0.0496, -0.0470, -0.0192, -0.0087, -0.0313]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2510, 0.2488, 0.2460, 0.2495, 0.2538],
        [0.2445, 0.2486, 0.2520, 0.2527, 0.2458],
        [0.2575, 0.2548, 0

Epoch 0:   2%|▏         | 273/12001 [00:04<02:00, 97.72batch/s, bias_accuracy=100.0%, bias_loss=1.2, debias_accuracy=25.0%, debias_loss=0.79] 

tensor([[-0.0590, -0.0462, -0.0199,  0.0120, -0.0562],
        [-0.0057, -0.0164, -0.0206, -0.0447, -0.0150],
        [-0.0588, -0.0620, -0.0055,  0.0058, -0.0367],
        [-0.0323, -0.0442, -0.0121, -0.0212, -0.0147]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2450, 0.2490, 0.2487, 0.2560, 0.2437],
        [0.2584, 0.2565, 0.2485, 0.2419, 0.2539],
        [0.2450, 0.2451, 0.2523, 0.2544, 0.2485],
        [0.2516, 0.2495, 0.2506, 0.2477, 0.2540]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7615, 0.7629, 0.7605, 0.7575], device='cuda:7', dtype=torch.float64)
tensor([[-0.0304, -0.0377, -0.0238, -0.0288, -0.0319],
        [-0.0367, -0.0300, -0.0097, -0.0209, -0.0380],
        [-0.0213, -0.0434, -0.0446, -0.0332, -0.0145],
        [-0.0398, -0.0451, -0.0253, -0.0202, -0.0205]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2504, 0.2503, 0.2505, 0.2492, 0.2486],
        [0.2488, 0.2523, 0.2541, 0.2512, 0.2471],
        [0.2527, 0.2489, 0

Epoch 0:   2%|▏         | 293/12001 [00:04<02:00, 97.42batch/s, bias_accuracy=25.0%, bias_loss=1.21, debias_accuracy=50.0%, debias_loss=0.804] 

tensor([[-0.0114, -0.0228, -0.0259, -0.0540, -0.0147],
        [-0.0355, -0.0417, -0.0179, -0.0244, -0.0149],
        [-0.0187, -0.0208, -0.0264, -0.0593, -0.0134],
        [-0.0454, -0.0460, -0.0273,  0.0207, -0.0343]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2541, 0.2525, 0.2496, 0.2438, 0.2512],
        [0.2480, 0.2478, 0.2516, 0.2511, 0.2511],
        [0.2523, 0.2530, 0.2495, 0.2425, 0.2515],
        [0.2456, 0.2467, 0.2493, 0.2627, 0.2463]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7603, 0.7565, 0.7592, 0.7654], device='cuda:7', dtype=torch.float64)
tensor([[-0.0409, -0.0261, -0.0250, -0.0115, -0.0287],
        [-0.0329, -0.0307, -0.0164, -0.0317, -0.0356],
        [-0.0385, -0.0345, -0.0411, -0.0314, -0.0054],
        [-0.0067, -0.0211, -0.0324, -0.0582, -0.0160]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2472, 0.2505, 0.2509, 0.2555, 0.2482],
        [0.2492, 0.2493, 0.2531, 0.2503, 0.2465],
        [0.2478, 0.2484, 0

Epoch 0:   3%|▎         | 314/12001 [00:04<02:00, 97.20batch/s, bias_accuracy=50.0%, bias_loss=1.21, debias_accuracy=0.0%, debias_loss=0.805] 

tensor([[-0.0157, -0.0421, -0.0098, -0.0426, -0.0087],
        [-0.0489, -0.0282, -0.0295, -0.0255, -0.0303],
        [-0.0363, -0.0421, -0.0339, -0.0168, -0.0222],
        [-0.0186, -0.0365, -0.0184, -0.0532, -0.0187]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2535, 0.2488, 0.2533, 0.2480, 0.2528],
        [0.2453, 0.2523, 0.2483, 0.2522, 0.2474],
        [0.2484, 0.2488, 0.2473, 0.2545, 0.2494],
        [0.2528, 0.2502, 0.2511, 0.2453, 0.2503]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7600, 0.7592, 0.7575, 0.7596], device='cuda:7', dtype=torch.float64)
tensor([[-0.0528, -0.0361, -0.0347, -0.0152, -0.0353],
        [-0.0051, -0.0320, -0.0252, -0.0486, -0.0182],
        [-0.0392, -0.0358, -0.0236, -0.0304, -0.0306],
        [-0.0300, -0.0301, -0.0203, -0.0263, -0.0282]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2448, 0.2493, 0.2478, 0.2537, 0.2482],
        [0.2567, 0.2504, 0.2502, 0.2454, 0.2525],
        [0.2481, 0.2494, 0

Epoch 0:   3%|▎         | 334/12001 [00:04<02:02, 95.41batch/s, bias_accuracy=75.0%, bias_loss=1.21, debias_accuracy=50.0%, debias_loss=0.792]

tensor([[-0.0609, -0.0573, -0.0422,  0.0086, -0.0407],
        [-0.0503, -0.0458, -0.0295, -0.0065, -0.0273],
        [-0.0466, -0.0446, -0.0198,  0.0165, -0.0538],
        [-0.0310, -0.0284, -0.0278, -0.0313, -0.0438]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2466, 0.2467, 0.2469, 0.2529, 0.2502],
        [0.2492, 0.2495, 0.2501, 0.2491, 0.2535],
        [0.2501, 0.2498, 0.2525, 0.2549, 0.2469],
        [0.2541, 0.2539, 0.2505, 0.2430, 0.2494]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7596, 0.7579, 0.7608, 0.7602], device='cuda:7', dtype=torch.float64)
tensor([[-0.0623, -0.0486, -0.0101,  0.0111, -0.0388],
        [-0.0101, -0.0202, -0.0306, -0.0521, -0.0130],
        [-0.0625, -0.0456, -0.0196, -0.0050, -0.0267],
        [-0.0501, -0.0360, -0.0446, -0.0117, -0.0333]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2460, 0.2473, 0.2540, 0.2564, 0.2473],
        [0.2591, 0.2544, 0.2489, 0.2407, 0.2538],
        [0.2459, 0.2480, 0

Epoch 0:   3%|▎         | 355/12001 [00:04<01:59, 97.56batch/s, bias_accuracy=25.0%, bias_loss=1.21, debias_accuracy=25.0%, debias_loss=0.804]

tensor([[-0.0348, -0.0279, -0.0155, -0.0329, -0.0281],
        [-0.0460, -0.0298, -0.0104, -0.0259, -0.0292],
        [-0.0751, -0.0567, -0.0246, -0.0050, -0.0378],
        [-0.0007, -0.0220, -0.0241, -0.0439, -0.0213]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2510, 0.2515, 0.2508, 0.2485, 0.2502],
        [0.2482, 0.2511, 0.2521, 0.2502, 0.2500],
        [0.2411, 0.2444, 0.2485, 0.2555, 0.2478],
        [0.2597, 0.2530, 0.2486, 0.2458, 0.2519]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7588, 0.7585, 0.7612, 0.7637], device='cuda:7', dtype=torch.float64)
tensor([[-0.0573, -0.0442, -0.0205,  0.0123, -0.0425],
        [-0.0379, -0.0350, -0.0174, -0.0336, -0.0329],
        [-0.0675, -0.0547, -0.0302,  0.0248, -0.0586],
        [-0.0589, -0.0461, -0.0345,  0.0057, -0.0351]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2495, 0.2502, 0.2513, 0.2525, 0.2499],
        [0.2544, 0.2525, 0.2521, 0.2411, 0.2524],
        [0.2470, 0.2476, 0

Epoch 0:   3%|▎         | 366/12001 [00:05<01:56, 99.72batch/s, bias_accuracy=25.0%, bias_loss=1.21, debias_accuracy=25.0%, debias_loss=0.801] 

tensor([[0.2535, 0.2534, 0.2523, 0.2487, 0.2488],
        [0.2494, 0.2506, 0.2515, 0.2488, 0.2496],
        [0.2495, 0.2473, 0.2486, 0.2560, 0.2495],
        [0.2477, 0.2487, 0.2476, 0.2465, 0.2520]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7600, 0.7575, 0.7576, 0.7565], device='cuda:7', dtype=torch.float64)
tensor([[-0.0111, -0.0158, -0.0356, -0.0429, -0.0170],
        [-0.0704, -0.0801, -0.0291,  0.0132, -0.0568],
        [-0.0717, -0.0586, -0.0339,  0.0404, -0.0663],
        [-0.0739, -0.0554, -0.0229,  0.0219, -0.0372]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2616, 0.2593, 0.2487, 0.2374, 0.2569],
        [0.2465, 0.2431, 0.2503, 0.2511, 0.2468],
        [0.2462, 0.2484, 0.2491, 0.2581, 0.2445],
        [0.2457, 0.2492, 0.2519, 0.2533, 0.2517]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7648, 0.7586, 0.7627, 0.7599], device='cuda:7', dtype=torch.float64)
tensor([[-0.0457, -0.0295, -0.0305, -0.0150, -0.0410],
        [-

Epoch 0:   3%|▎         | 387/12001 [00:05<01:55, 100.43batch/s, bias_accuracy=50.0%, bias_loss=1.21, debias_accuracy=25.0%, debias_loss=0.795]

tensor([[-0.0532, -0.0258, -0.0366, -0.0123, -0.0401],
        [-0.0200, -0.0324, -0.0225, -0.0410, -0.0050],
        [-0.0605, -0.0448, -0.0255,  0.0032, -0.0448],
        [-0.0087, -0.0223, -0.0382, -0.0431, -0.0171]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2456, 0.2514, 0.2485, 0.2527, 0.2467],
        [0.2539, 0.2497, 0.2521, 0.2456, 0.2555],
        [0.2438, 0.2466, 0.2513, 0.2567, 0.2455],
        [0.2568, 0.2523, 0.2481, 0.2450, 0.2524]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7587, 0.7602, 0.7586, 0.7619], device='cuda:7', dtype=torch.float64)
tensor([[-0.0336, -0.0358, -0.0144, -0.0348, -0.0036],
        [-0.0709, -0.0451, -0.0104,  0.0287, -0.0544],
        [-0.0488, -0.0470, -0.0449, -0.0259, -0.0324],
        [-0.0304, -0.0300, -0.0251, -0.0171, -0.0334]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2531, 0.2509, 0.2523, 0.2444, 0.2569],
        [0.2438, 0.2486, 0.2533, 0.2604, 0.2442],
        [0.2492, 0.2481, 0

Epoch 0:   3%|▎         | 408/12001 [00:05<01:57, 98.87batch/s, bias_accuracy=50.0%, bias_loss=1.21, debias_accuracy=25.0%, debias_loss=0.799] 

tensor([[0.2408, 0.2444, 0.2489, 0.2591, 0.2422],
        [0.2585, 0.2543, 0.2499, 0.2428, 0.2560],
        [0.2500, 0.2481, 0.2484, 0.2484, 0.2533],
        [0.2507, 0.2531, 0.2528, 0.2497, 0.2485]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7633, 0.7630, 0.7599, 0.7598], device='cuda:7', dtype=torch.float64)
tensor([[-0.0825, -0.0569, -0.0328,  0.0391, -0.0488],
        [-0.0625, -0.0370, -0.0296,  0.0069, -0.0435],
        [-0.0786, -0.0724, -0.0323,  0.0338, -0.0515],
        [-0.0363, -0.0277, -0.0131, -0.0155, -0.0421]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2456, 0.2479, 0.2485, 0.2558, 0.2494],
        [0.2506, 0.2529, 0.2493, 0.2476, 0.2507],
        [0.2466, 0.2441, 0.2487, 0.2544, 0.2488],
        [0.2572, 0.2552, 0.2535, 0.2422, 0.2511]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7613, 0.7574, 0.7605, 0.7610], device='cuda:7', dtype=torch.float64)
tensor([[-0.0864, -0.0577, -0.0145,  0.0541, -0.0789],
        [-

Epoch 0:   4%|▎         | 428/12001 [00:05<01:59, 97.24batch/s, bias_accuracy=0.0%, bias_loss=1.22, debias_accuracy=0.0%, debias_loss=0.815]  

tensor([[-0.0744, -0.0479, -0.0231,  0.0022, -0.0466],
        [-0.0705, -0.0554, -0.0295,  0.0541, -0.0603],
        [-0.0416, -0.0258, -0.0162, -0.0123, -0.0421],
        [-0.0425, -0.0205, -0.0216, -0.0097, -0.0531]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2457, 0.2474, 0.2499, 0.2483, 0.2510],
        [0.2467, 0.2455, 0.2483, 0.2616, 0.2476],
        [0.2539, 0.2529, 0.2516, 0.2447, 0.2521],
        [0.2537, 0.2542, 0.2502, 0.2454, 0.2493]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7578, 0.7647, 0.7596, 0.7604], device='cuda:7', dtype=torch.float64)
tensor([[-0.0362, -0.0281, -0.0286, -0.0157, -0.0329],
        [-0.0500, -0.0508, -0.0354, -0.0157, -0.0278],
        [-0.0493, -0.0394, -0.0166, -0.0090, -0.0345],
        [-0.0672, -0.0567, -0.0151,  0.0104, -0.0386]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2536, 0.2539, 0.2488, 0.2479, 0.2501],
        [0.2502, 0.2482, 0.2471, 0.2480, 0.2514],
        [0.2503, 0.2511, 0

Epoch 0:   4%|▎         | 448/12001 [00:05<01:58, 97.20batch/s, bias_accuracy=75.0%, bias_loss=1.19, debias_accuracy=25.0%, debias_loss=0.791] 

tensor([[-0.0108, -0.0291, -0.0343, -0.0326, -0.0152],
        [-0.0611, -0.0563, -0.0294,  0.0429, -0.0479],
        [-0.0478, -0.0273, -0.0081, -0.0205, -0.0387],
        [-0.0629, -0.0406, -0.0411,  0.0116, -0.0416]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2588, 0.2523, 0.2485, 0.2418, 0.2552],
        [0.2461, 0.2455, 0.2497, 0.2608, 0.2470],
        [0.2494, 0.2528, 0.2551, 0.2447, 0.2493],
        [0.2457, 0.2494, 0.2468, 0.2527, 0.2485]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7631, 0.7643, 0.7595, 0.7559], device='cuda:7', dtype=torch.float64)
tensor([[-0.0823, -0.0667, -0.0357,  0.0559, -0.0682],
        [-0.0244, -0.0329, -0.0396, -0.0191, -0.0183],
        [-0.0250, -0.0193, -0.0374, -0.0302, -0.0276],
        [-0.0421, -0.0298, -0.0513, -0.0136, -0.0317]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2404, 0.2427, 0.2513, 0.2647, 0.2421],
        [0.2547, 0.2510, 0.2503, 0.2456, 0.2545],
        [0.2546, 0.2545, 0

Epoch 0:   4%|▍         | 468/12001 [00:06<02:00, 95.67batch/s, bias_accuracy=25.0%, bias_loss=1.2, debias_accuracy=25.0%, debias_loss=0.805] 

tensor([[-0.0870, -0.0650, -0.0222,  0.0425, -0.0713],
        [-0.0731, -0.0404, -0.0238,  0.0223, -0.0681],
        [-0.0224, -0.0303, -0.0307, -0.0411, -0.0204],
        [-0.0527, -0.0332, -0.0214, -0.0177, -0.0307]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2430, 0.2443, 0.2506, 0.2603, 0.2441],
        [0.2464, 0.2504, 0.2502, 0.2551, 0.2449],
        [0.2592, 0.2530, 0.2485, 0.2394, 0.2568],
        [0.2515, 0.2522, 0.2508, 0.2451, 0.2542]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7640, 0.7580, 0.7633, 0.7592], device='cuda:7', dtype=torch.float64)
tensor([[-0.0622, -0.0388, -0.0371,  0.0164, -0.0635],
        [-0.0700, -0.0495, -0.0192,  0.0007, -0.0477],
        [-0.0366, -0.0260, -0.0396, -0.0083, -0.0357],
        [-0.0388, -0.0397, -0.0552, -0.0125, -0.0155]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2474, 0.2499, 0.2502, 0.2544, 0.2443],
        [0.2455, 0.2472, 0.2547, 0.2504, 0.2482],
        [0.2538, 0.2531, 0

Epoch 0:   4%|▍         | 488/12001 [00:06<02:00, 95.71batch/s, bias_accuracy=25.0%, bias_loss=1.2, debias_accuracy=0.0%, debias_loss=0.806]  

tensor([[-0.0412, -0.0484, -0.0315, -0.0100, -0.0216],
        [-0.0404, -0.0403, -0.0477, -0.0081, -0.0098],
        [-0.0742, -0.0413, -0.0338,  0.0147, -0.0504],
        [-0.0775, -0.0649, -0.0124,  0.0631, -0.0459]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2543, 0.2501, 0.2499, 0.2437, 0.2526],
        [0.2545, 0.2521, 0.2459, 0.2442, 0.2556],
        [0.2460, 0.2518, 0.2494, 0.2498, 0.2454],
        [0.2452, 0.2460, 0.2548, 0.2622, 0.2465]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7594, 0.7612, 0.7575, 0.7651], device='cuda:7', dtype=torch.float64)
tensor([[-0.0434, -0.0193, -0.0190, -0.0218, -0.0497],
        [-0.0401, -0.0219, -0.0214, -0.0091, -0.0499],
        [-0.0867, -0.0727, -0.0396,  0.0558, -0.0537],
        [-0.0106, -0.0151, -0.0401, -0.0390, -0.0090]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2504, 0.2532, 0.2528, 0.2453, 0.2477],
        [0.2512, 0.2525, 0.2522, 0.2484, 0.2476],
        [0.2397, 0.2400, 0

Epoch 0:   4%|▍         | 508/12001 [00:06<02:03, 92.69batch/s, bias_accuracy=25.0%, bias_loss=1.21, debias_accuracy=25.0%, debias_loss=0.796]

tensor([[0.2548, 0.2535, 0.2545, 0.2439, 0.2513],
        [0.2556, 0.2554, 0.2485, 0.2427, 0.2517],
        [0.2540, 0.2514, 0.2495, 0.2447, 0.2528],
        [0.2356, 0.2397, 0.2475, 0.2687, 0.2442]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7608, 0.7612, 0.7603, 0.7689], device='cuda:7', dtype=torch.float64)
tensor([[-0.0768, -0.0616, -0.0242,  0.0465, -0.0603],
        [-0.0867, -0.0561, -0.0124,  0.0549, -0.0772],
        [-0.0409, -0.0159, -0.0186, -0.0070, -0.0428],
        [-0.0081, -0.0082, -0.0360, -0.0441, -0.0219]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2440, 0.2435, 0.2496, 0.2584, 0.2475],
        [0.2416, 0.2448, 0.2526, 0.2606, 0.2434],
        [0.2530, 0.2549, 0.2510, 0.2449, 0.2519],
        [0.2614, 0.2568, 0.2467, 0.2360, 0.2572]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7629, 0.7642, 0.7608, 0.7646], device='cuda:7', dtype=torch.float64)
tensor([[-0.0752, -0.0555, -0.0429,  0.0628, -0.0615],
        [-

Epoch 0:   4%|▍         | 529/12001 [00:06<02:01, 94.78batch/s, bias_accuracy=50.0%, bias_loss=1.2, debias_accuracy=0.0%, debias_loss=0.798]  

tensor([[0.2393, 0.2433, 0.2532, 0.2635, 0.2430],
        [0.2601, 0.2575, 0.2456, 0.2419, 0.2539],
        [0.2495, 0.2510, 0.2535, 0.2472, 0.2494],
        [0.2511, 0.2482, 0.2476, 0.2475, 0.2536]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7658, 0.7639, 0.7585, 0.7600], device='cuda:7', dtype=torch.float64)
tensor([[-0.0557, -0.0199, -0.0368, -0.0038, -0.0558],
        [-0.0672, -0.0414, -0.0248,  0.0188, -0.0655],
        [-0.0979, -0.0655, -0.0391,  0.0817, -0.1096],
        [-0.0896, -0.0693, -0.0516,  0.0816, -0.0613]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2555, 0.2573, 0.2503, 0.2380, 0.2543],
        [0.2526, 0.2519, 0.2533, 0.2435, 0.2518],
        [0.2449, 0.2459, 0.2497, 0.2593, 0.2410],
        [0.2470, 0.2449, 0.2466, 0.2592, 0.2529]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7623, 0.7599, 0.7634, 0.7634], device='cuda:7', dtype=torch.float64)
tensor([[-0.0409, -0.0250, -0.0162, -0.0112, -0.0495],
        [-

Epoch 0:   5%|▍         | 549/12001 [00:06<01:59, 95.66batch/s, bias_accuracy=50.0%, bias_loss=1.21, debias_accuracy=75.0%, debias_loss=0.792] 

tensor([[-0.0360, -0.0331, -0.0593, -0.0042, -0.0175],
        [-0.0394, -0.0165, -0.0376,  0.0032, -0.0614],
        [-0.0729, -0.0491, -0.0082,  0.0065, -0.0548],
        [-0.0743, -0.0423, -0.0303,  0.0277, -0.0568]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2549, 0.2505, 0.2437, 0.2469, 0.2576],
        [0.2541, 0.2547, 0.2490, 0.2487, 0.2465],
        [0.2457, 0.2466, 0.2565, 0.2495, 0.2482],
        [0.2453, 0.2482, 0.2508, 0.2549, 0.2477]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7624, 0.7607, 0.7617, 0.7584], device='cuda:7', dtype=torch.float64)
tensor([[-0.0703, -0.0356, -0.0288,  0.0230, -0.0775],
        [-0.0262, -0.0368, -0.0622, -0.0017, -0.0273],
        [-0.0388, -0.0344, -0.0642, -0.0006, -0.0241],
        [-0.0419, -0.0397, -0.0574, -0.0075, -0.0246]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2436, 0.2503, 0.2561, 0.2550, 0.2403],
        [0.2545, 0.2500, 0.2477, 0.2487, 0.2527],
        [0.2513, 0.2506, 0

Epoch 0:   5%|▍         | 569/12001 [00:07<02:01, 94.27batch/s, bias_accuracy=50.0%, bias_loss=1.2, debias_accuracy=75.0%, debias_loss=0.786]   

tensor([[-0.0608, -0.0254, -0.0338, -0.0011, -0.0550],
        [-0.0694, -0.0342, -0.0339,  0.0366, -0.0662],
        [-0.0723, -0.0450, -0.0271,  0.0312, -0.0746],
        [-0.0822, -0.0604, -0.0332,  0.0948, -0.0903]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2526, 0.2540, 0.2495, 0.2397, 0.2541],
        [0.2504, 0.2517, 0.2495, 0.2489, 0.2513],
        [0.2497, 0.2491, 0.2512, 0.2476, 0.2492],
        [0.2473, 0.2452, 0.2497, 0.2638, 0.2453]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7603, 0.7576, 0.7586, 0.7661], device='cuda:7', dtype=torch.float64)
tensor([[-0.0423, -0.0131, -0.0263,  0.0006, -0.0590],
        [-0.1034, -0.0652, -0.0402,  0.0846, -0.0959],
        [-0.1001, -0.0672, -0.0406,  0.0961, -0.0807],
        [-0.0407, -0.0264, -0.0178, -0.0064, -0.0447]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2573, 0.2575, 0.2512, 0.2392, 0.2527],
        [0.2421, 0.2444, 0.2478, 0.2601, 0.2436],
        [0.2429, 0.2440, 0

Epoch 0:   5%|▍         | 579/12001 [00:07<02:04, 91.47batch/s, bias_accuracy=75.0%, bias_loss=1.2, debias_accuracy=50.0%, debias_loss=0.794] 

tensor([[-0.0425, -0.0160, -0.0249, -0.0035, -0.0493],
        [-0.1008, -0.0753, -0.0562,  0.0831, -0.0691],
        [-0.0454, -0.0329, -0.0193,  0.0041, -0.0443],
        [-0.0734, -0.0400, -0.0351,  0.0305, -0.0737]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2558, 0.2563, 0.2522, 0.2420, 0.2525],
        [0.2413, 0.2415, 0.2445, 0.2639, 0.2475],
        [0.2550, 0.2520, 0.2537, 0.2438, 0.2537],
        [0.2480, 0.2502, 0.2497, 0.2504, 0.2464]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7616, 0.7661, 0.7591, 0.7577], device='cuda:7', dtype=torch.float64)
tensor([[-0.0726, -0.0422, -0.0234,  0.0252, -0.0740],
        [-0.0047, -0.0200, -0.0497, -0.0383, -0.0209],
        [-0.0389, -0.0306, -0.0661, -0.0180, -0.0153],
        [-0.0900, -0.0542, -0.0177,  0.0642, -0.0671]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2447, 0.2486, 0.2539, 0.2541, 0.2426],
        [0.2618, 0.2542, 0.2473, 0.2384, 0.2558],
        [0.2531, 0.2515, 0

Epoch 0:   5%|▍         | 599/12001 [00:07<02:03, 92.36batch/s, bias_accuracy=50.0%, bias_loss=1.19, debias_accuracy=50.0%, debias_loss=0.794]

tensor([[-0.0972, -0.0803, -0.0393,  0.1026, -0.0762],
        [-0.1115, -0.0709, -0.0427,  0.1002, -0.1003],
        [-0.0389, -0.0343, -0.0489,  0.0100, -0.0278],
        [-0.0560, -0.0177, -0.0382, -0.0141, -0.0475]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2446, 0.2427, 0.2507, 0.2632, 0.2466],
        [0.2412, 0.2449, 0.2499, 0.2626, 0.2407],
        [0.2593, 0.2541, 0.2483, 0.2399, 0.2588],
        [0.2549, 0.2583, 0.2510, 0.2342, 0.2538]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7657, 0.7653, 0.7631, 0.7628], device='cuda:7', dtype=torch.float64)
tensor([[-0.0362, -0.0294, -0.0245, -0.0153, -0.0383],
        [-0.0665, -0.0354, -0.0330,  0.0358, -0.0727],
        [-0.0275, -0.0444, -0.0573,  0.0042, -0.0142],
        [-0.0097, -0.0125, -0.0524, -0.0487, -0.0222]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2496, 0.2502, 0.2543, 0.2476, 0.2496],
        [0.2422, 0.2487, 0.2522, 0.2605, 0.2411],
        [0.2518, 0.2465, 0

Epoch 0:   5%|▌         | 619/12001 [00:07<02:02, 93.12batch/s, bias_accuracy=0.0%, bias_loss=1.22, debias_accuracy=0.0%, debias_loss=0.805]  

tensor([[ 0.0029, -0.0100, -0.0432, -0.0431, -0.0244],
        [-0.0934, -0.0917, -0.0247,  0.0887, -0.0843],
        [-0.0749, -0.0475, -0.0246,  0.0229, -0.0677],
        [-0.0467, -0.0146, -0.0406, -0.0004, -0.0628]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2642, 0.2577, 0.2475, 0.2351, 0.2589],
        [0.2399, 0.2375, 0.2521, 0.2683, 0.2439],
        [0.2444, 0.2482, 0.2522, 0.2512, 0.2480],
        [0.2514, 0.2565, 0.2482, 0.2454, 0.2492]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7663, 0.7686, 0.7592, 0.7618], device='cuda:7', dtype=torch.float64)
tensor([[-0.0687, -0.0539, -0.0341,  0.0372, -0.0554],
        [-0.0425, -0.0269, -0.0313,  0.0063, -0.0496],
        [-0.0982, -0.0654, -0.0407,  0.1104, -0.0916],
        [ 0.0024, -0.0086, -0.0462, -0.0361, -0.0186]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2456, 0.2462, 0.2510, 0.2516, 0.2495],
        [0.2522, 0.2529, 0.2517, 0.2439, 0.2510],
        [0.2385, 0.2433, 0

Epoch 0:   5%|▌         | 639/12001 [00:07<02:00, 94.48batch/s, bias_accuracy=50.0%, bias_loss=1.19, debias_accuracy=50.0%, debias_loss=0.788] 

tensor([[-0.0816, -0.0553, -0.0205,  0.0546, -0.0700],
        [-0.0812, -0.0498, -0.0287,  0.0614, -0.0810],
        [-0.0369, -0.0270, -0.0161, -0.0037, -0.0396],
        [-0.0998, -0.0667, -0.0198,  0.0954, -0.0873]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2483, 0.2486, 0.2502, 0.2505, 0.2498],
        [0.2483, 0.2499, 0.2481, 0.2522, 0.2471],
        [0.2596, 0.2557, 0.2513, 0.2363, 0.2575],
        [0.2438, 0.2458, 0.2504, 0.2609, 0.2455]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7580, 0.7567, 0.7613, 0.7644], device='cuda:7', dtype=torch.float64)
tensor([[-0.0421, -0.0535, -0.0590,  0.0152, -0.0273],
        [-0.0991, -0.0701, -0.0273,  0.1202, -0.0882],
        [-0.0094, -0.0294, -0.0375, -0.0273, -0.0274],
        [-0.1034, -0.0775, -0.0340,  0.0815, -0.0983]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2552, 0.2510, 0.2451, 0.2417, 0.2582],
        [0.2411, 0.2469, 0.2530, 0.2684, 0.2430],
        [0.2637, 0.2571, 0

Epoch 0:   5%|▌         | 660/12001 [00:08<01:56, 97.27batch/s, bias_accuracy=25.0%, bias_loss=1.19, debias_accuracy=25.0%, debias_loss=0.8]  

tensor([[-0.1149, -0.0884, -0.0404,  0.1025, -0.0829],
        [-0.0306, -0.0253, -0.0244, -0.0035, -0.0578],
        [-0.0404, -0.0253, -0.0194, -0.0073, -0.0570],
        [-0.0786, -0.0579, -0.0234,  0.0544, -0.0642]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2380, 0.2403, 0.2466, 0.2668, 0.2457],
        [0.2589, 0.2560, 0.2506, 0.2399, 0.2519],
        [0.2564, 0.2560, 0.2519, 0.2390, 0.2521],
        [0.2468, 0.2478, 0.2509, 0.2542, 0.2503]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7678, 0.7614, 0.7614, 0.7584], device='cuda:7', dtype=torch.float64)
tensor([[ 0.0094, -0.0122, -0.0425, -0.0340, -0.0319],
        [-0.0824, -0.0658, -0.0165,  0.0573, -0.0723],
        [-0.1132, -0.0771, -0.0297,  0.1253, -0.0970],
        [-0.0361, -0.0228, -0.0262, -0.0070, -0.0607]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2665, 0.2581, 0.2466, 0.2328, 0.2585],
        [0.2431, 0.2446, 0.2531, 0.2551, 0.2482],
        [0.2358, 0.2419, 0

Epoch 0:   6%|▌         | 682/12001 [00:08<01:52, 100.71batch/s, bias_accuracy=50.0%, bias_loss=1.21, debias_accuracy=50.0%, debias_loss=0.8]   

tensor([0.7648, 0.7644, 0.7612, 0.7719], device='cuda:7', dtype=torch.float64)
tensor([[-0.0826, -0.0529, -0.0163,  0.0656, -0.0853],
        [-0.0708, -0.0487, -0.0345,  0.0519, -0.0704],
        [-0.0979, -0.0714, -0.0028,  0.1058, -0.0980],
        [-0.1098, -0.0799, -0.0319,  0.1315, -0.1133]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2519, 0.2526, 0.2513, 0.2442, 0.2516],
        [0.2549, 0.2536, 0.2467, 0.2408, 0.2554],
        [0.2481, 0.2479, 0.2547, 0.2542, 0.2484],
        [0.2451, 0.2458, 0.2474, 0.2608, 0.2446]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7586, 0.7559, 0.7604, 0.7643], device='cuda:7', dtype=torch.float64)
tensor([[-0.0351, -0.0146, -0.0335, -0.0015, -0.0617],
        [-0.0644, -0.0499, -0.0197,  0.0449, -0.0877],
        [-0.0215, -0.0537, -0.0401,  0.0005, -0.0272],
        [-0.0357, -0.0258, -0.0263, -0.0175, -0.0566]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2510, 0.2554, 0.2491, 0.2479, 0.2491

Epoch 0:   6%|▌         | 704/12001 [00:08<01:51, 101.56batch/s, bias_accuracy=75.0%, bias_loss=1.16, debias_accuracy=75.0%, debias_loss=0.774]  

tensor([[-0.0399, -0.0204, -0.0238, -0.0024, -0.0601],
        [-0.0747, -0.0622, -0.0180,  0.0531, -0.0699],
        [ 0.0162, -0.0133, -0.0444, -0.0362, -0.0311],
        [-0.1146, -0.0986, -0.0387,  0.1313, -0.0978]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2531, 0.2570, 0.2518, 0.2400, 0.2511],
        [0.2444, 0.2465, 0.2533, 0.2537, 0.2486],
        [0.2677, 0.2588, 0.2467, 0.2320, 0.2585],
        [0.2349, 0.2377, 0.2481, 0.2743, 0.2418]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7621, 0.7599, 0.7683, 0.7721], device='cuda:7', dtype=torch.float64)
tensor([[-0.0042, -0.0358, -0.0448, -0.0294, -0.0268],
        [ 0.0137, -0.0144, -0.0408, -0.0424, -0.0256],
        [ 0.0138, -0.0094, -0.0374, -0.0480, -0.0289],
        [-0.0216, -0.0154, -0.0236, -0.0103, -0.0602]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2488, 0.2458, 0.2480, 0.2508, 0.2521],
        [0.2533, 0.2511, 0.2490, 0.2475, 0.2524],
        [0.2533, 0.2523, 0

Epoch 0:   6%|▌         | 726/12001 [00:08<01:52, 99.91batch/s, bias_accuracy=25.0%, bias_loss=1.2, debias_accuracy=25.0%, debias_loss=0.787]  

tensor([[-0.0294, -0.0468, -0.0477, -0.0123, -0.0208],
        [-0.0305, -0.0643, -0.0510,  0.0152, -0.0288],
        [-0.0989, -0.0903, -0.0300,  0.1341, -0.1066],
        [-0.0421, -0.0284, -0.0386, -0.0079, -0.0471]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2552, 0.2526, 0.2485, 0.2387, 0.2575],
        [0.2549, 0.2482, 0.2477, 0.2453, 0.2554],
        [0.2380, 0.2419, 0.2530, 0.2763, 0.2363],
        [0.2519, 0.2573, 0.2508, 0.2397, 0.2508]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7623, 0.7611, 0.7732, 0.7622], device='cuda:7', dtype=torch.float64)
tensor([[-0.0197, -0.0538, -0.0589,  0.0129, -0.0213],
        [-0.0224, -0.0511, -0.0596,  0.0015, -0.0115],
        [-0.0230, -0.0593, -0.0645,  0.0130, -0.0135],
        [-0.0682, -0.0493, -0.0318,  0.0487, -0.0814]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2534, 0.2499, 0.2487, 0.2484, 0.2526],
        [0.2527, 0.2506, 0.2485, 0.2456, 0.2551],
        [0.2525, 0.2485, 0

Epoch 0:   6%|▌         | 748/12001 [00:08<01:50, 101.58batch/s, bias_accuracy=75.0%, bias_loss=1.18, debias_accuracy=50.0%, debias_loss=0.784]  

tensor([[-0.0145, -0.0463, -0.0600,  0.0003, -0.0192],
        [ 0.0235, -0.0351, -0.0496, -0.0391, -0.0228],
        [-0.1183, -0.0930, -0.0255,  0.1509, -0.1327],
        [-0.1205, -0.0928, -0.0339,  0.1319, -0.1118]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2604, 0.2551, 0.2456, 0.2345, 0.2631],
        [0.2705, 0.2580, 0.2482, 0.2254, 0.2622],
        [0.2348, 0.2435, 0.2542, 0.2726, 0.2349],
        [0.2343, 0.2435, 0.2521, 0.2675, 0.2398]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7656, 0.7699, 0.7711, 0.7682], device='cuda:7', dtype=torch.float64)
tensor([[-0.0023, -0.0365, -0.0388, -0.0340, -0.0264],
        [ 0.0314, -0.0079, -0.0381, -0.0488, -0.0236],
        [-0.0850, -0.0470, -0.0147,  0.0499, -0.0900],
        [-0.0776, -0.0501, -0.0306,  0.0588, -0.0804]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2576, 0.2497, 0.2479, 0.2398, 0.2572],
        [0.2664, 0.2569, 0.2481, 0.2363, 0.2579],
        [0.2371, 0.2471, 0

Epoch 0:   6%|▋         | 770/12001 [00:09<01:50, 101.51batch/s, bias_accuracy=0.0%, bias_loss=1.22, debias_accuracy=0.0%, debias_loss=0.809]  

tensor([0.7592, 0.7606, 0.7591, 0.7605], device='cuda:7', dtype=torch.float64)
tensor([[-0.0900, -0.0675, -0.0248,  0.0661, -0.0768],
        [-0.1174, -0.1084, -0.0149,  0.1596, -0.1187],
        [-0.0772, -0.0649, -0.0156,  0.0502, -0.0825],
        [ 0.0294, -0.0085, -0.0450, -0.0472, -0.0147]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2431, 0.2485, 0.2500, 0.2516, 0.2489],
        [0.2366, 0.2386, 0.2525, 0.2762, 0.2387],
        [0.2463, 0.2492, 0.2524, 0.2476, 0.2475],
        [0.2740, 0.2637, 0.2450, 0.2246, 0.2649]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7579, 0.7731, 0.7593, 0.7719], device='cuda:7', dtype=torch.float64)
tensor([[ 0.0252, -0.0242, -0.0467, -0.0509, -0.0226],
        [-0.0909, -0.1018, -0.0213,  0.1540, -0.0911],
        [-0.0275, -0.0216, -0.0290, -0.0079, -0.0547],
        [-0.1127, -0.0868, -0.0016,  0.1491, -0.1133]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2695, 0.2586, 0.2445, 0.2226, 0.2621

Epoch 0:   7%|▋         | 792/12001 [00:09<01:51, 100.75batch/s, bias_accuracy=0.0%, bias_loss=1.21, debias_accuracy=0.0%, debias_loss=0.803]  

tensor([[-0.0336, -0.0263, -0.0304,  0.0019, -0.0581],
        [-0.0316, -0.0589, -0.0635, -0.0011, -0.0228],
        [ 0.0317, -0.0162, -0.0495, -0.0562, -0.0164],
        [-0.0117, -0.0606, -0.0460,  0.0030, -0.0430]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2444, 0.2535, 0.2542, 0.2537, 0.2443],
        [0.2449, 0.2454, 0.2460, 0.2529, 0.2531],
        [0.2609, 0.2561, 0.2494, 0.2394, 0.2547],
        [0.2498, 0.2450, 0.2503, 0.2540, 0.2480]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7600, 0.7597, 0.7644, 0.7566], device='cuda:7', dtype=torch.float64)
tensor([[-0.0265, -0.0220, -0.0254, -0.0073, -0.0625],
        [-0.0995, -0.0899, -0.0264,  0.1598, -0.1180],
        [ 0.0252, -0.0081, -0.0535, -0.0395, -0.0242],
        [ 0.0216, -0.0137, -0.0500, -0.0526, -0.0231]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2480, 0.2527, 0.2533, 0.2436, 0.2484],
        [0.2306, 0.2361, 0.2531, 0.2878, 0.2350],
        [0.2612, 0.2563, 0

Epoch 0:   7%|▋         | 803/12001 [00:09<01:52, 99.62batch/s, bias_accuracy=25.0%, bias_loss=1.19, debias_accuracy=25.0%, debias_loss=0.789] 

tensor([[0.2508, 0.2522, 0.2529, 0.2428, 0.2500],
        [0.2408, 0.2414, 0.2518, 0.2674, 0.2453],
        [0.2698, 0.2627, 0.2458, 0.2201, 0.2680],
        [0.2386, 0.2436, 0.2494, 0.2697, 0.2367]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7596, 0.7681, 0.7695, 0.7694], device='cuda:7', dtype=torch.float64)
tensor([[-0.0159, -0.0544, -0.0649, -0.0019, -0.0266],
        [-0.0243, -0.0315, -0.0253, -0.0137, -0.0573],
        [-0.1334, -0.1191, -0.0326,  0.1531, -0.0948],
        [-0.1289, -0.1167, -0.0251,  0.1655, -0.1086]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2650, 0.2564, 0.2431, 0.2305, 0.2614],
        [0.2628, 0.2623, 0.2529, 0.2278, 0.2535],
        [0.2356, 0.2403, 0.2511, 0.2692, 0.2442],
        [0.2367, 0.2409, 0.2529, 0.2725, 0.2408]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7647, 0.7652, 0.7691, 0.7710], device='cuda:7', dtype=torch.float64)
tensor([[-0.0895, -0.0694, -0.0163,  0.0678, -0.0850],
        [-

Epoch 0:   7%|▋         | 824/12001 [00:09<01:52, 99.14batch/s, bias_accuracy=25.0%, bias_loss=1.18, debias_accuracy=0.0%, debias_loss=0.791] 

tensor([[ 0.0292, -0.0195, -0.0485, -0.0501, -0.0139],
        [ 0.0348, -0.0046, -0.0484, -0.0395, -0.0273],
        [-0.1340, -0.1173, -0.0510,  0.1563, -0.0874],
        [-0.0236, -0.0197, -0.0441, -0.0143, -0.0575]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2629, 0.2550, 0.2499, 0.2338, 0.2582],
        [0.2644, 0.2588, 0.2499, 0.2363, 0.2547],
        [0.2233, 0.2312, 0.2493, 0.2875, 0.2399],
        [0.2494, 0.2549, 0.2510, 0.2424, 0.2472]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7655, 0.7664, 0.7793, 0.7608], device='cuda:7', dtype=torch.float64)
tensor([[-0.0181, -0.0520, -0.0728, -0.0043, -0.0010],
        [-0.0303, -0.0209, -0.0335, -0.0058, -0.0533],
        [-0.0917, -0.0551, -0.0090,  0.0681, -0.0906],
        [-0.1162, -0.1130, -0.0275,  0.1908, -0.1120]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2615, 0.2519, 0.2408, 0.2331, 0.2661],
        [0.2584, 0.2599, 0.2505, 0.2328, 0.2525],
        [0.2430, 0.2511, 0

Epoch 0:   7%|▋         | 844/12001 [00:10<01:54, 97.19batch/s, bias_accuracy=25.0%, bias_loss=1.18, debias_accuracy=25.0%, debias_loss=0.784]  

tensor([[-0.0275, -0.0278, -0.0341, -0.0141, -0.0409],
        [ 0.0246, -0.0306, -0.0519, -0.0403, -0.0182],
        [ 0.0332, -0.0200, -0.0495, -0.0535, -0.0156],
        [-0.0948, -0.0717, -0.0220,  0.0660, -0.0755]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2469, 0.2524, 0.2513, 0.2488, 0.2491],
        [0.2601, 0.2517, 0.2469, 0.2424, 0.2548],
        [0.2623, 0.2544, 0.2475, 0.2392, 0.2555],
        [0.2308, 0.2416, 0.2544, 0.2696, 0.2406]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7593, 0.7639, 0.7652, 0.7605], device='cuda:7', dtype=torch.float64)
tensor([[-0.0242, -0.0617, -0.0712,  0.0009,  0.0070],
        [-0.0398, -0.0735, -0.0773,  0.0138, -0.0265],
        [ 0.0254, -0.0157, -0.0498, -0.0497, -0.0103],
        [-0.0257, -0.0713, -0.0537, -0.0017, -0.0051]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2479, 0.2484, 0.2479, 0.2525, 0.2539],
        [0.2441, 0.2455, 0.2464, 0.2557, 0.2456],
        [0.2605, 0.2601, 0

Epoch 0:   7%|▋         | 864/12001 [00:10<01:55, 96.26batch/s, bias_accuracy=75.0%, bias_loss=1.17, debias_accuracy=75.0%, debias_loss=0.773] 

tensor([[ 0.0251, -0.0302, -0.0688, -0.0591, -0.0045],
        [-0.1453, -0.1150, -0.0278,  0.1993, -0.1365],
        [-0.1352, -0.1157, -0.0168,  0.1655, -0.1199],
        [-0.0176, -0.0229, -0.0288, -0.0062, -0.0486]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2737, 0.2601, 0.2418, 0.2173, 0.2685],
        [0.2308, 0.2390, 0.2519, 0.2814, 0.2353],
        [0.2332, 0.2388, 0.2547, 0.2721, 0.2392],
        [0.2623, 0.2621, 0.2516, 0.2292, 0.2569]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7717, 0.7760, 0.7708, 0.7650], device='cuda:7', dtype=torch.float64)
tensor([[ 0.0255, -0.0263, -0.0533, -0.0508, -0.0194],
        [-0.1207, -0.1062, -0.0382,  0.1828, -0.1530],
        [-0.0246, -0.0577, -0.0742,  0.0050, -0.0308],
        [-0.0319, -0.0132, -0.0359,  0.0007, -0.0664]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2660, 0.2561, 0.2492, 0.2287, 0.2619],
        [0.2298, 0.2364, 0.2530, 0.2888, 0.2292],
        [0.2530, 0.2481, 0

Epoch 0:   7%|▋         | 884/12001 [00:10<01:56, 95.63batch/s, bias_accuracy=25.0%, bias_loss=1.18, debias_accuracy=0.0%, debias_loss=0.785]  

tensor([[0.2306, 0.2376, 0.2578, 0.2897, 0.2373],
        [0.2570, 0.2574, 0.2452, 0.2309, 0.2550],
        [0.2737, 0.2575, 0.2419, 0.2240, 0.2640],
        [0.2386, 0.2475, 0.2551, 0.2554, 0.2437]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7805, 0.7623, 0.7717, 0.7610], device='cuda:7', dtype=torch.float64)
tensor([[-0.0182, -0.0251, -0.0207, -0.0147, -0.0518],
        [-0.0324, -0.0178, -0.0494, -0.0005, -0.0498],
        [-0.0170, -0.0574, -0.0798, -0.0056, -0.0040],
        [-0.0843, -0.0651, -0.0322,  0.0723, -0.0724]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2549, 0.2540, 0.2562, 0.2431, 0.2481],
        [0.2513, 0.2559, 0.2490, 0.2465, 0.2486],
        [0.2552, 0.2460, 0.2415, 0.2453, 0.2602],
        [0.2386, 0.2441, 0.2533, 0.2652, 0.2431]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7603, 0.7614, 0.7640, 0.7598], device='cuda:7', dtype=torch.float64)
tensor([[-0.1480, -0.1162, -0.0453,  0.1930, -0.1205],
        [-

Epoch 0:   8%|▊         | 904/12001 [00:10<01:57, 94.38batch/s, bias_accuracy=75.0%, bias_loss=1.16, debias_accuracy=75.0%, debias_loss=0.767]

tensor([0.7638, 0.7743, 0.7767, 0.7729], device='cuda:7', dtype=torch.float64)
tensor([[ 0.0401, -0.0187, -0.0517, -0.0594, -0.0123],
        [-0.1054, -0.0587, -0.0237,  0.0811, -0.1065],
        [-0.1301, -0.1013, -0.0115,  0.1811, -0.1237],
        [-0.0925, -0.0671, -0.0115,  0.0805, -0.0895]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2790, 0.2608, 0.2433, 0.2187, 0.2681],
        [0.2412, 0.2506, 0.2502, 0.2517, 0.2440],
        [0.2354, 0.2401, 0.2533, 0.2781, 0.2398],
        [0.2444, 0.2485, 0.2533, 0.2515, 0.2481]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7747, 0.7580, 0.7742, 0.7598], device='cuda:7', dtype=torch.float64)
tensor([[-0.0093, -0.0556, -0.0707,  0.0058, -0.0119],
        [-0.1563, -0.1328, -0.0330,  0.2194, -0.1229],
        [-0.0527, -0.0664, -0.0480,  0.0134, -0.0197],
        [-0.1111, -0.0718, -0.0004,  0.1079, -0.1178]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2685, 0.2565, 0.2419, 0.2297, 0.2641

Epoch 0:   8%|▊         | 924/12001 [00:10<01:58, 93.32batch/s, bias_accuracy=50.0%, bias_loss=1.13, debias_accuracy=50.0%, debias_loss=0.763]  

tensor([[0.2312, 0.2420, 0.2573, 0.2715, 0.2390],
        [0.2696, 0.2583, 0.2444, 0.2299, 0.2610],
        [0.2686, 0.2575, 0.2429, 0.2282, 0.2612],
        [0.2306, 0.2422, 0.2553, 0.2705, 0.2389]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7623, 0.7694, 0.7688, 0.7610], device='cuda:7', dtype=torch.float64)
tensor([[-0.1397, -0.1185, -0.0360,  0.2193, -0.1465],
        [-0.0941, -0.0747,  0.0080,  0.0717, -0.0957],
        [-0.0327, -0.0231, -0.0527, -0.0012, -0.0541],
        [-0.0365, -0.0670, -0.0507,  0.0182, -0.0291]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2343, 0.2382, 0.2491, 0.2871, 0.2340],
        [0.2452, 0.2489, 0.2603, 0.2477, 0.2462],
        [0.2607, 0.2621, 0.2450, 0.2303, 0.2567],
        [0.2598, 0.2508, 0.2455, 0.2348, 0.2631]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7791, 0.7640, 0.7650, 0.7657], device='cuda:7', dtype=torch.float64)
tensor([[-0.1302, -0.1177, -0.0278,  0.2117, -0.1401],
        [ 

Epoch 0:   8%|▊         | 944/12001 [00:11<01:57, 94.15batch/s, bias_accuracy=50.0%, bias_loss=1.17, debias_accuracy=50.0%, debias_loss=0.778]  

tensor([[-0.0940, -0.0765, -0.0246,  0.1038, -0.0942],
        [-0.0351, -0.0301, -0.0346, -0.0034, -0.0567],
        [-0.1595, -0.1324, -0.0332,  0.2407, -0.1572],
        [ 0.0537, -0.0124, -0.0649, -0.0584, -0.0057]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2406, 0.2463, 0.2537, 0.2567, 0.2457],
        [0.2552, 0.2580, 0.2512, 0.2306, 0.2551],
        [0.2253, 0.2330, 0.2515, 0.2944, 0.2307],
        [0.2789, 0.2627, 0.2437, 0.2183, 0.2685]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7601, 0.7627, 0.7830, 0.7746], device='cuda:7', dtype=torch.float64)
tensor([[-0.0202, -0.0237, -0.0339, -0.0054, -0.0534],
        [-0.0855, -0.0731, -0.0074,  0.0806, -0.1017],
        [ 0.0450, -0.0237, -0.0755, -0.0648, -0.0121],
        [-0.0304, -0.0282, -0.0406, -0.0193, -0.0481]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2504, 0.2533, 0.2513, 0.2489, 0.2500],
        [0.2345, 0.2411, 0.2580, 0.2712, 0.2382],
        [0.2672, 0.2533, 0

Epoch 0:   8%|▊         | 964/12001 [00:11<01:57, 93.67batch/s, bias_accuracy=50.0%, bias_loss=1.17, debias_accuracy=50.0%, debias_loss=0.776]  

tensor([[0.2391, 0.2498, 0.2564, 0.2573, 0.2414],
        [0.2419, 0.2433, 0.2465, 0.2586, 0.2555],
        [0.2616, 0.2552, 0.2492, 0.2398, 0.2526],
        [0.2573, 0.2517, 0.2479, 0.2443, 0.2505]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7577, 0.7611, 0.7648, 0.7622], device='cuda:7', dtype=torch.float64)
tensor([[-0.0296, -0.0224, -0.0384, -0.0107, -0.0626],
        [-0.0273, -0.0261, -0.0327, -0.0123, -0.0591],
        [-0.0245, -0.0686, -0.0694,  0.0020, -0.0141],
        [-0.1002, -0.0769,  0.0102,  0.1045, -0.1269]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2539, 0.2565, 0.2485, 0.2419, 0.2506],
        [0.2544, 0.2556, 0.2499, 0.2416, 0.2514],
        [0.2552, 0.2449, 0.2409, 0.2450, 0.2630],
        [0.2366, 0.2429, 0.2608, 0.2715, 0.2350]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7618, 0.7612, 0.7656, 0.7643], device='cuda:7', dtype=torch.float64)
tensor([[-4.0480e-02, -2.9827e-02, -3.9836e-02, -2.5301e-02, -4.0

Epoch 0:   8%|▊         | 984/12001 [00:11<01:58, 92.67batch/s, bias_accuracy=25.0%, bias_loss=1.2, debias_accuracy=25.0%, debias_loss=0.794]   

tensor([[-0.0037, -0.0688, -0.0761, -0.0032, -0.0191],
        [ 0.0707, -0.0015, -0.0552, -0.0795, -0.0192],
        [ 0.0546, -0.0173, -0.0561, -0.0705, -0.0101],
        [-0.1726, -0.1423, -0.0273,  0.2358, -0.1562]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2511, 0.2468, 0.2444, 0.2421, 0.2577],
        [0.2705, 0.2640, 0.2496, 0.2243, 0.2577],
        [0.2662, 0.2599, 0.2493, 0.2263, 0.2600],
        [0.2121, 0.2293, 0.2566, 0.3074, 0.2247]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7625, 0.7699, 0.7675, 0.7898], device='cuda:7', dtype=torch.float64)
tensor([[-0.0394, -0.0623, -0.0821,  0.0223, -0.0182],
        [-0.1489, -0.1299, -0.0183,  0.2234, -0.1279],
        [-0.1054, -0.0744, -0.0051,  0.1046, -0.1058],
        [-0.0120, -0.0563, -0.0725, -0.0021, -0.0105]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2591, 0.2545, 0.2406, 0.2334, 0.2618],
        [0.2322, 0.2379, 0.2565, 0.2854, 0.2346],
        [0.2425, 0.2515, 0

Epoch 0:   8%|▊         | 1004/12001 [00:11<01:56, 94.04batch/s, bias_accuracy=50.0%, bias_loss=1.16, debias_accuracy=50.0%, debias_loss=0.777]

tensor([[-0.0989, -0.0739,  0.0054,  0.0771, -0.0948],
        [ 0.0431, -0.0293, -0.0737, -0.0691, -0.0075],
        [ 0.0708, -0.0204, -0.0658, -0.0753, -0.0083],
        [-0.0176, -0.0188, -0.0347, -0.0121, -0.0595]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2261, 0.2405, 0.2621, 0.2749, 0.2371],
        [0.2606, 0.2515, 0.2421, 0.2375, 0.2587],
        [0.2680, 0.2538, 0.2440, 0.2361, 0.2585],
        [0.2453, 0.2542, 0.2517, 0.2515, 0.2456]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7650, 0.7642, 0.7685, 0.7604], device='cuda:7', dtype=torch.float64)
tensor([[-0.1060, -0.0708, -0.0075,  0.0872, -0.1152],
        [-0.1047, -0.0832, -0.0086,  0.1021, -0.1138],
        [-0.1484, -0.1256, -0.0037,  0.2352, -0.1587],
        [-0.0179, -0.0583, -0.0832, -0.0047, -0.0203]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2468, 0.2534, 0.2545, 0.2447, 0.2464],
        [0.2471, 0.2502, 0.2542, 0.2484, 0.2468],
        [0.2365, 0.2399, 0

Epoch 0:   8%|▊         | 1014/12001 [00:11<01:57, 93.22batch/s, bias_accuracy=75.0%, bias_loss=1.15, debias_accuracy=75.0%, debias_loss=0.759]

tensor([[-0.0267, -0.0206, -0.0323, -0.0153, -0.0595],
        [ 0.0669, -0.0164, -0.0670, -0.0748, -0.0014],
        [-0.0956, -0.0637, -0.0230,  0.0759, -0.1150],
        [-0.1133, -0.0737, -0.0032,  0.0991, -0.1137]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2533, 0.2557, 0.2497, 0.2404, 0.2530],
        [0.2781, 0.2568, 0.2412, 0.2266, 0.2681],
        [0.2364, 0.2449, 0.2520, 0.2634, 0.2393],
        [0.2322, 0.2425, 0.2571, 0.2696, 0.2396]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7613, 0.7742, 0.7591, 0.7621], device='cuda:7', dtype=torch.float64)
tensor([[-0.1110, -0.0826,  0.0087,  0.1098, -0.1222],
        [-0.0219, -0.0230, -0.0235, -0.0188, -0.0559],
        [-0.0993, -0.0877,  0.0115,  0.0884, -0.1012],
        [-0.0051, -0.0137, -0.0402, -0.0313, -0.0494]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2371, 0.2423, 0.2549, 0.2683, 0.2401],
        [0.2593, 0.2572, 0.2468, 0.2360, 0.2565],
        [0.2400, 0.2410, 0

Epoch 0:   9%|▊         | 1034/12001 [00:12<01:54, 95.57batch/s, bias_accuracy=75.0%, bias_loss=1.16, debias_accuracy=50.0%, debias_loss=0.773] 

tensor([[0.2712, 0.2599, 0.2435, 0.2165, 0.2675],
        [0.2268, 0.2402, 0.2565, 0.2837, 0.2286],
        [0.2720, 0.2613, 0.2439, 0.2106, 0.2719],
        [0.2301, 0.2387, 0.2561, 0.2892, 0.2320]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7682, 0.7773, 0.7707, 0.7803], device='cuda:7', dtype=torch.float64)
tensor([[ 0.0051, -0.0612, -0.0812, -0.0062, -0.0263],
        [ 0.0731, -0.0180, -0.0814, -0.0728, -0.0133],
        [-0.1794, -0.1519, -0.0293,  0.2642, -0.1545],
        [-0.1707, -0.1484, -0.0221,  0.2989, -0.1829]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2673, 0.2581, 0.2431, 0.2173, 0.2668],
        [0.2861, 0.2695, 0.2430, 0.2033, 0.2703],
        [0.2223, 0.2357, 0.2560, 0.2847, 0.2347],
        [0.2242, 0.2366, 0.2579, 0.2948, 0.2281]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7678, 0.7786, 0.7778, 0.7832], device='cuda:7', dtype=torch.float64)
tensor([[ 0.0740, -0.0104, -0.0668, -0.0855, -0.0071],
        [-

Epoch 0:   9%|▉         | 1055/12001 [00:12<01:52, 97.64batch/s, bias_accuracy=50.0%, bias_loss=1.11, debias_accuracy=50.0%, debias_loss=0.75]   

tensor([[ 0.0736, -0.0108, -0.0802, -0.0966, -0.0253],
        [-0.1201, -0.0908,  0.0190,  0.1100, -0.1138],
        [-0.1712, -0.1559, -0.0135,  0.2929, -0.1672],
        [ 0.0631, -0.0212, -0.0683, -0.0733, -0.0116]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2781, 0.2647, 0.2389, 0.2114, 0.2634],
        [0.2291, 0.2444, 0.2638, 0.2600, 0.2411],
        [0.2177, 0.2290, 0.2554, 0.3121, 0.2285],
        [0.2752, 0.2620, 0.2418, 0.2164, 0.2670]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7742, 0.7661, 0.7923, 0.7725], device='cuda:7', dtype=torch.float64)
tensor([[-0.1266, -0.0825, -0.0121,  0.1264, -0.1241],
        [-0.1611, -0.1342, -0.0162,  0.2129, -0.1479],
        [-0.0149, -0.0523, -0.0774,  0.0158, -0.0250],
        [ 0.0030, -0.0553, -0.0933, -0.0130, -0.0027]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2368, 0.2495, 0.2594, 0.2594, 0.2376],
        [0.2288, 0.2369, 0.2584, 0.2828, 0.2319],
        [0.2648, 0.2572, 0

Epoch 0:   9%|▉         | 1079/12001 [00:12<02:06, 86.66batch/s, bias_accuracy=50.0%, bias_loss=1.15, debias_accuracy=50.0%, debias_loss=0.766] 

tensor([[ 0.0855, -0.0047, -0.0664, -0.0897, -0.0113],
        [ 0.0871, -0.0179, -0.0708, -0.0887, -0.0092],
        [-0.0227, -0.0198, -0.0264, -0.0092, -0.0571],
        [-0.0241, -0.0228, -0.0400, -0.0146, -0.0691]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2635, 0.2529, 0.2461, 0.2402, 0.2563],
        [0.2639, 0.2496, 0.2450, 0.2405, 0.2569],
        [0.2365, 0.2491, 0.2562, 0.2604, 0.2449],
        [0.2361, 0.2484, 0.2527, 0.2590, 0.2419]], device='cuda:7',
       grad_fn=<SoftmaxBackward0>)
tensor([0.7659, 0.7661, 0.7573, 0.7569], device='cuda:7', dtype=torch.float64)
tensor([[-0.1221, -0.0746,  0.0065,  0.1281, -0.1520],
        [ 0.0080, -0.0615, -0.0614, -0.0014, -0.0176],
        [-0.2034, -0.1679, -0.0210,  0.3303, -0.2029],
        [-0.0305, -0.0168, -0.0429, -0.0219, -0.0643]], device='cuda:7',
       grad_fn=<AddmmBackward0>)
tensor([[0.2406, 0.2510, 0.2591, 0.2523, 0.2389],
        [0.2740, 0.2543, 0.2421, 0.2217, 0.2733],
        [0.2218, 0.2287, 0

KeyboardInterrupt: 

In [ ]:
from spuco.evaluate import Evaluator

evaluator = Evaluator(
    testset=testset,
    group_partition=testset.group_partition,
    group_weights=trainset.group_weights,
    batch_size=64,
    model=bias_model,
    device=device,
    verbose=True
)
evaluator.evaluate()

In [ ]:
evaluator.worst_group_accuracy

In [ ]:
evaluator.average_accuracy

In [ ]:
evaluator.evaluate_spurious_task()

In [8]:
import torch
from torch import nn 

a = torch.tensor([[1., 2.], [2., 4.]])
torch.softmax(a, dim=0)

tensor([[0.2689, 0.1192],
        [0.7311, 0.8808]])